### ISSUE TITLE
Build fails without Conduit

### ISSUE THREAD

**Issue by timmoon10** [LLNL/lbann#1001]
I tried building LBANN with the following command on Pascal:
```sh
scripts/build_lbann_lc.sh --verbose --clean-build
```

This results in errors like:

```
/usr/WS1/moon13/src/lbann/src/data_readers/data_reader.cpp: In member function 'virtual int lbann::generic_data_reader::fetch_data(lbann::CPUMat&, El::Matrix<long long int>&)':
/usr/WS1/moon13/src/lbann/src/data_readers/data_reader.cpp:118:17: error: invalid use of incomplete type 'class lbann::data_store_conduit'
     m_data_store->exchange_mini_batch_data(m_current_pos-m_base_offset-m_model_offset, loaded_batch_size);
                 ^
In file included from /usr/WS1/moon13/src/lbann/src/data_readers/data_reader.cpp:29:0:
/usr/WS1/moon13/src/lbann/include/lbann/data_readers/data_reader.hpp:56:7: error: forward declaration of 'class lbann::data_store_conduit'
 class data_store_conduit;
```

The error is probably from PR #984. In particular:

https://github.com/LLNL/lbann/blob/c0f0062441e185eed552ac7dc7ff60646c1eb15b/include/lbann/data_readers/data_reader.hpp#L743

`lbann::generic_data_reader::m_data_store` has been changed from a `lbann::generic_data_store*` to a `lbann::data_store_conduit*`.

**Comment by davidHysom** [comment]
I need to consult with Brian. There's been discussion as to making conduit a requirement for building lbann. Since our data readers will be increasingly relying on data_store_conduit for improved performance, perhaps we should make it so.
That said, I'll take a look after lunch about fixing the bug.

**Comment by ndryden** [comment]
If our default build will not compile without conduit, it should be required.

**Comment by davidHysom** [comment]
While we can continue to stick "#ifdef LBANN_HAS_CONDUIT" in various places to enable building without conduit, I suspect the better choice is to require conduit. If you want to use the data store for (the increasing) number of data readers that support it. And why wouldn't you, since the data store reduces I/O hence, improves runtime?

**Comment by bvanessen** [comment]
We should move to making conduit a fully integrated part of LBANN.

**Comment by ndryden** [comment]
> And why wouldn't you, since the data store reduces I/O hence, improves runtime?

This is only true if I/O is the bottleneck and not fully overlapped by computation. Worst case, using the data store could potentially increase network traffic and hurt overall runtime.

**Comment by bvanessen** [comment]
I don’t think that we should force the data store to be used by default, but building with support for it is not unreasonable.  Plus we want to move to a path where all data readers can use the data store, which means that they will integrated conduit support for execution even without the data store.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by ndryden** [comment]
👆 This I agree with.

**Comment by davidHysom** [comment]
So where do we go from here? Paging Tom?

**Comment by benson31** [comment]
If you're asking how to make it required, in the CMake, just stick a `REQUIRED` in the last of the `find_package(Conduit ...)` calls. Then CMake will throw an error (specifically `FATAL_ERROR`) if Conduit isn't found.

**Comment by davidHysom** [comment]
closing, since this has been fixes. Lbann now always builds with conduit, and --with-conduit in the build script is no longer required.
