### ISSUE TITLE
JAG reader failure to read from PFS

### ISSUE THREAD

**Issue by samadejacobs** [LLNL/lbann#1002]
Error message (typically occur without data store and preload flags, confirmed on pascal/lustre, haven't tried on lassen/gpfs)

LBANN error on rank 2 (/usr/WS1/jacobs32/git.saj.sc19/src/data_readers/data_reader_jag_conduit.cpp:374): data_reader_jag_conduit:: Cannot open file /3/samples_201_13.bundle for sample 0.4.72.79.48:5

**Comment by bvanessen** [comment]
Closed in PR #1016
