### ISSUE TITLE
Layer::forward/back_prop copies too much

### ISSUE THREAD

**Issue by ndryden** [LLNL/lbann#101]
When converting data distributions, `Layer::forward_prop` and `back_prop` copy the entire forward/backward input. This means it copies excess data when the current mini-batch size is smaller than the maximum mini-batch size, which slows things down a lot.

Unfortunately, I haven't figured out a nice way to avoid this without data reallocation. Copying into a view just replaces the viewing matrix with the copied data, instead of copying into the viewed sub-matrix. Doing a trick with attaching matrices doesn't seem to work because that will free the existing data in the matrix doing the attach.

What we need is some sort of "copy matrix into a submatrix" method, but I can't find an Elemental method to do this. Maybe @timmoon10 has some ideas?

**Comment by timmoon10** [comment]
Fixed in 4f237378f1ff7718c4d4d9d859615fc94dae344d.
