### ISSUE TITLE
Gradient checking

### ISSUE THREAD

**Issue by timmoon10** [LLNL/lbann#102]
Checking gradients would be a good way to verify that LBANN is working correctly. Thoughts:
- It would be very useful to incorporate this into a unit test.
- We currently do not include L2 regularization terms into the objective function.
- We should research how other frameworks handle discontinuities in the gradient (from reLU, max pooling).

**Comment by ndryden** [comment]
Note the code used to have some methods to do this, but I'm pretty sure they're all broken now.

The [UFLDL tutorial](http://ufldl.stanford.edu/tutorial/supervised/DebuggingGradientChecking/) has a brief section on this.

**Comment by timmoon10** [comment]
A gradient check callback is implemented in 0be2850225258e7db1fc0da1070fde9534841524. Next steps: verify our layers are correct and write unit tests.

**Comment by bvanessen** [comment]
Awesome.  Can you please work with Dylan and Ryan to get them helping out with the unit tests.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470
