### ISSUE TITLE
Support random crop data augmentation

### ISSUE THREAD

**Issue by ndryden** [LLNL/lbann#104]
A common method of data augmentation is to randomly crop input images to a fixed size. For example, AlexNet and ResNet both randomly crop the input 256x256 ImageNet images to 224x224 images.

We should support this in the image preprocessor. This is probably pretty similar to the random patch work being done.

(Note also this should improve the training time of AlexNet, etc.: the first convolution will be over a smaller image.)

**Comment by JaeseungYeom** [comment]
In fact, I added resizer for this reason. However, I have not used it in the pipeline yet. The resizer can crop and scale as specified by the parameters. For random cropping, the parameters needs to be randomized.  It could be done by itself or handed over. Currently, only the latter works, but as you said it can be done similarly as random patch generation without much of changes.

**Comment by bvanessen** [comment]
What is the current state of updating the imagenet cv data reader?

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by JaeseungYeom** [comment]
I have updated OpenCV recipe for using 3.3.0.
However, I am not able to run tests yet due to the issue #106 reported.
I have dnn_imagenet that is updated based on the interface usage shown in cnn_mnist, which crashes for me at the moment. Once this problem is sorted out, I will run the performance tests.

**Comment by timmoon10** [comment]
In principle, we support this on GPUs with the crop layer.
