### ISSUE TITLE
NVCC does not support the latest(?) clang yet and causes compilation error as below

### ISSUE THREAD

**Issue by JaeseungYeom** [LLNL/lbann#105]
[ 80%] Building NVCC (Device) object CMakeFiles/lbann.dir/src/utils/lbann_generated_cudnn_wrapper_cuda.cu.o
nvcc fatal   : The version ('40000') of the host compiler ('clang') is not supported
CMake Error at lbann_generated_cudnn_wrapper_cuda.cu.o.cmake:207 (message):
  Error generating
  /p/lscratche/yeom2/LBANN/lbann/build/surface.llnl.gov/CMakeFiles/lbann.dir/src/utils/./lbann_generated_cudnn_wrapper_cuda.cu.o

Do we have an option not to use nvcc?

**Comment by naoyam** [comment]
Currently, no. Can we just use compatible versions?

**Comment by JaeseungYeom** [comment]
I will try that.
However, even using gcc I am getting the following error on ray.
This is probably a different issue.

[ 82%] Building NVCC (Device) object CMakeFiles/lbann.dir/src/utils/lbann_generated_cudnn_wrapper_cuda.cu.o
CMake Warning (dev) at lbann_generated_cudnn_wrapper_cuda.cu.o.Release.cmake:81:
  Syntax Warning in cmake code at column 51

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.

nvcc fatal   : Stray '"' character
CMake Error at lbann_generated_cudnn_wrapper_cuda.cu.o.Release.cmake:222 (message):
  Error generating
  /p/gscratchr/yeom2/LBANN/lbann/build/ray.llnl.gov/CMakeFiles/lbann.dir/src/utils/./lbann_generated_cudnn_wrapper_cuda.cu.o

**Comment by trb413** [comment]
The reason for the error you're seeing with GCC is that the LBANN version string has non-escaped quotation marks in it, e.g. `"some-lbann-version-string"`. Then the cmake-generated wrapper script writes this into its `CUDA_NVCC_COMPILE_DEFINITIONS` using something like this:

`
set(CUDA_NVCC_COMPILE_DEFINITIONS "LBANN_VERSION="some-lbann-version-string";...OTHER_THINGS)
`

so the quotes around `some-lbann-version-string` break the set quotes causing this parse error. I'm working on a fix for this. In the meantime, you can edit that file and set the line to be:

`
set(CUDA_NVCC_COMPILE_DEFINITIONS "LBANN_VERSION=\"some-lbann-version-string\";...OTHER_THINGS)
`

(note the escaped quotes).
