### ISSUE TITLE
epoch completion detection issue

### ISSUE THREAD

**Issue by JaeseungYeom** [LLNL/lbann#106]
model_zoo/cnn_mnist has error as below. Note that I am printing out extra information about member variables. I am using 8 ranks total.

LBANN: rank 7 of model 0 caught error message:  /p/lscratchh/yeom2/LBANN/lbann/src/data_readers/data_reader.cpp 62
m_base_offset 896
m_sample_stride 1
m_mini_batch_stride 1024
m_last_mini_batch_stride 1024
m_current_mini_batch_idx 423
m_num_iterations_per_epoch 422
m_global_mini_batch_size  128
m_global_last_mini_batch_size 128
srun: mvapich: 2017-08-21T16:30:25: ABORT from MPI rank 7 [on surface107] dest rank 1 [on surface60]
slurmd[surface60]: *** STEP 1730409.0 KILLED AT 2017-08-21T16:30:25 WITH SIGNAL 9 ***
slurmd[surface61]: *** STEP 1730409.0 KILLED AT 2017-08-21T16:30:25 WITH SIGNAL 9 ***
slurmd[surface62]: *** STEP 1730409.0 KILLED AT 2017-08-21T16:30:25 WITH SIGNAL 9 ***
srun: mvapich: 2017-08-21T16:30:25: ABORT from MPI rank 6 [on surface107] dest rank 1 [on surface60]
slurmd[surface60]: *** STEP 1730409.0 KILLED AT 2017-08-21T16:30:25 WITH SIGNAL 9 ***
 :: generic data reader load error: !position_valid -- current pos = 54144 and there are 54000 indices
PMGR_COLLECTIVE ERROR: rank 7 on surface107: Called pmgr_abort() Code: 1, Msg: application called MPI_Abort(MPI_COMM_WORLD, 1) - process 7
LBANN: rank 6 of model 0 caught error message:  /p/lscratchh/yeom2/LBANN/lbann/src/data_readers/data_reader.cpp 62
m_base_offset 768
m_sample_stride 1
m_mini_batch_stride 1024
m_last_mini_batch_stride 1024
m_current_mini_batch_idx 422
m_num_iterations_per_epoch 422
m_global_mini_batch_size  128
m_global_last_mini_batch_size 128
 :: generic data reader load error: !position_valid -- current pos = 54016 and there are 54000 indices
PMGR_COLLECTIVE ERROR: rank 6 on surface107: Called pmgr_abort() Code: 1, Msg: application called MPI_Abort(MPI_COMM_WORLD, 1) - process 6
slurmd[surface107]: *** STEP 1730409.0 KILLED AT 2017-08-21T16:30:25 WITH SIGNAL 9 ***
slurmd[surface107]: *** STEP 1730409.0 KILLED AT 2017-08-21T16:30:25 WITH SIGNAL 9 ***
slurmd[surface62]: *** STEP 1730409.0 KILLED AT 2017-08-21T16:30:25 WITH SIGNAL 9 ***
slurmd[surface61]: *** STEP 1730409.0 KILLED AT 2017-08-21T16:30:25 WITH SIGNAL 9 ***

-------------------------------------------
We have a loop for an epoch as

void evaluate()
{
  do {
    finished_epoch = evaluate_mini_batch();
  } while(!finished_epoch);
}

bool evaluate_mini_batch()
{
  for (size_t l = 0u; l < m_layers.size(); l++) {
    m_layers[l]->forward_prop();
  }
  for (size_t l = m_layers.size() - 1; l > 0u; --l) {
    m_layers[l]->update();
  }
  const bool data_set_processed = m_layers[0]->update();
  return data_set_processed;
}

I think update() should return false when there no more data to process.
Otherwise, it would run forward prop more than it should and cause accessing non-existent minibatches.

**Comment by ndryden** [comment]
`cnn_mnist` uses the distributed input/target layers, which have a known issue @bvanessen is working on. In the meantime, try with the partitioned input/target layers, those should work.

**Comment by bvanessen** [comment]
This is fixed in 62fcc4e79df57e076a5bc40cf65f3a9d80097a60
