### ISSUE TITLE
Clean up dead code

### ISSUE THREAD

**Issue by ndryden** [LLNL/lbann#11]
There's a lot of dead code lying around, or code that's broken but needs to work eventually. We should probably just delete it all and add issues for what needs to be implemented. The old code will still be around in version control if needed.

Off the top of my head, the biggest offender is probably the checkpointing code, which is almost certainly broken.

**Comment by davidHysom** [comment]
Can this be closed? I believe Adam did a lot of work on the checkpointing code, but I don't know if it works -- meaning, has anyone used it and/or do we have a test? I believe the "dead code" issue has mostly been addressed in our June 2017 refactoring effort.

**Comment by ndryden** [comment]
The checkpoint code worked before the recent refactoring, but has not been updated after our recent refactoring.

Still, this is reasonable to close, #26 tracks the checkpoint/restart issues.
