### ISSUE TITLE
Data readers always shuffle data

### ISSUE THREAD

**Issue by ndryden** [LLNL/lbann#111]
The shuffle parameter to `generic_data_reader` is ignored.

**Comment by davidHysom** [comment]
There is a field, "bool shuffle," in the prototext "message Reader." proto_common.cpp passes this value to the various data reader ctors, and data_reader.cpp appears to only shuffle is the value is true.

That said, my question is: why do you think data readers always shuffle?

We need some sort of tests (unit?) for this. (unf. I'm a novice at writing unit tests)

**Comment by ndryden** [comment]
Because both parameters to the `generic_data_reader` ctor are ignored (see [line 65](https://github.com/LLNL/lbann/blob/develop/include/lbann/data_readers/data_reader.hpp#L65)).

Shuffling is done when `m_first_n` is `false`, and it's initialized that way. (Unless something explicitly calls `set_firstN(false)`.)

See also #113.

Tests would be very welcome.

**Comment by davidHysom** [comment]
ouch. I will fix that.

________________________________

**Comment by davidHysom** [comment]
Data readers now correctly respects the shuffle argument. added a quasi-unit test: tests/test_shuffled_indices.cpp
