### ISSUE TITLE
Using no test dataset hangs

### ISSUE THREAD

**Issue by ndryden** [LLNL/lbann#115]
(Might be related to #114.)

Running with `train_or_test_percent: 0.0` on the _test_ dataset results in LBANN hanging after training/validation completes.

**Comment by ndryden** [comment]
Probably caused by calling `evaluate` despite having no data, though ultimately the bug lies in either `evaluate` (if there's no data for the execution mode, it should bail) or the layers (they should work with no data).

It seems different ranks have gotten out of order: some are stuck in the allreduce in computing categorical accuracy, while rank 0 is off doing its own thing and apparently not stuck in any collective. (I haven't surveyed all the ranks.)

**Comment by ndryden** [comment]
Looks like _something_ is getting out of sync, regardless. Looking at it in GDB, rank 1 has `m_current_testing_step = 265735`.

Rank 0 is stuck in the allreduce in `learning::l2_regularize_objective_function`, and has `m_current_testing_step = 269764`.

Rank 2 is also in `learning::l2_regularize_objective_function`, and has `m_current_testing_step = 298648`.

**Comment by ndryden** [comment]
Looks like the check in `m_cur_step_in_epoch == (num_iterations_per_epoch - 1)` in `partitioned_minibatch::is_data_set_processed` is wrong when `num_iterations_per_epoch` is 0, since the subtraction means we compare against a negative number.

**Comment by bvanessen** [comment]
I have a different way to fix this that I used for when the validation does not have any samples.  I am testing it now.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by bvanessen** [comment]
I added guards that stop the models from evaluating when there are no relevant data sets.  3ff040c8ce337da3f4454492ae391c3baba4b923
