### ISSUE TITLE
Allow data readers to use partial paths to data sets with command line full path prefix override

### ISSUE THREAD

**Issue by bvanessen** [LLNL/lbann#116]
Our data readers currently provide a full path to the data set.  When using these at different locations, they may have the same relative path for the given data set, but the root path to where the data set is located will be different.  We should allow a command line argument to say where the base of the data set is, and then have the data reader specific the "local, internal" paths.

**Comment by davidHysom** [comment]
This is in place (pretty much?); may be ongoing developemnt as the sample_list class and files are further developed.
