### ISSUE TITLE
Preprocessor macro with a quoted string results in a CMake error

### ISSUE THREAD

**Issue by naoyam** [LLNL/lbann#117]
LBANN_VERSION is set as "VERSION_NAME" in CMakeLists.txt:

`add_definitions(-DLBANN_VERSION=\"v0.UKWN\")`

This results in a CMake error as it also quotes the macro definitions:

`set(CUDA_NVCC_COMPILE_DEFINITIONS "LBANN_VERSION="v0.UKWN"LBANN_FULLY_CONNECTED_CUDA;LBANN_TOPO_AWARE;LBANN_PARALLEL_RANDOM_MATRICES;LBANN_DATATYPE=4;__LIB_OPENCV;__LIB_CUDA;__LIB_CUDNN;__LIB_ELEMENTAL") # list (needs to be in quotes to handle spaces properly).`
 
This seems to happen only with CUDA compilation. I'm using CMake 3.9.2. I have not observed this problem before.

**Comment by naoyam** [comment]
This can be worked around by removing quotation in macro definitions and stringifying them when used in source code. See https://gcc.gnu.org/onlinedocs/cpp/Stringizing.html#Stringizing.

Specifically, for macro LBANN_VERSION, in CMakeLists.txt:

`add_definitions(-DLBANN_VERSION=v0.UKWN)`

And, at a common header file, add the following preprocessing functions:

    #define MAKE_STR(x) _MAKE_STR(x)
    #define _MAKE_STR(x) #x

When using the LBANN_VERSION macro, call MAKE_STR as shown below:

    char *lbann_version = MAKE_STR(LBANN_VERSION) // expanded as "v0.UKWN"

This is a little more complicated than just passing quoted strings as macro definitions. However, quotation in CMake is frequently a source of headache. 

Does anyone have any comment? If not, I'll fix this issue with the above workaround.

**Comment by bvanessen** [comment]
That looks great.  Thanks.


Brian C. Van Essen

vanessen1@llnl.gov<mailto:vanessen1@llnl.gov>

(w) 925-422-9300

(c) 925-290-5470

---

Sent from my iPhone

On Oct 4, 2017, at 8:20 PM, Naoya Maruyama <notifications@github.com<mailto:notifications@github.com>> wrote:


This can be worked around by removing quotation in macro definitions and stringifying them when used in source code. See https://gcc.gnu.org/onlinedocs/cpp/Stringizing.html#Stringizing.

Specifically, for macro LBANN_VERSION, in CMakeLists.txt:

add_definitions(-DLBANN_VERSION=v0.UKWN)

And, at a common header file, add the following preprocessing functions:

#define MAKE_STR(x) _MAKE_STR(x)
#define _MAKE_STR(x) #x


When using the LBANN_VERSION macro, call MAKE_STR as shown below:

char *lbann_version = MAKE_STR(LBANN_VERSION) // expanded as "v0.UKWN"


This is a little more complicated than just passing quoted strings as macro definitions. However, quotation in CMake is frequently a source of headache.

Does anyone have any comment? If not, I'll fix this issue with the above workaround.

**Comment by naoyam** [comment]
OK. Applied: 6bc92862b4998df3afd58ff869aa7d4dde058c54
