### ISSUE TITLE
Move trainer's pair hash to utility function

### ISSUE THREAD

**Issue by bvanessen** [LLNL/lbann#1222]
>  This should probably move to "utils" or something. Perhaps near where execution_mode is declared/defined.

**Comment by ndryden** [comment]
Don't bring in boost, just adapt the hash function.

**Comment by timmoon10** [comment]
From what I've googled, combining hashes with XOR is not great. [Boost's `hash_combine`](https://www.boost.org/doc/libs/1_55_0/doc/html/hash/reference.html#boost.hash_combine) has a magic one-liner which we can copy-paste.
