### ISSUE TITLE
Testing on a copy of a previously trained network

### ISSUE THREAD

**Issue by samadejacobs** [LLNL/lbann#125]
It seems that some of recent changes might have caused copying model to fail. A simple test will be to validate/test  a copy of a previously trained network.  I confirm this potential bug by adding two lines to the file [link](https://github.com/LLNL/lbann/blob/develop/model_zoo/historical/cnn_mnist.cpp)
deep_neural_network* cp_dnn = dnn.copy();
 cp_dnn->evaluate(execution_mode::testing);

Result: Model 0 @79 testing steps external validation categorical accuracy: -nan%

**Comment by ndryden** [comment]
This appears to be fixed with ae64b038116feddc448663cbbd6f9ede8fc7d8a6.

Reopen if not.
