### ISSUE TITLE
Number of Neurons from Data Reader

### ISSUE THREAD

**Issue by samadejacobs** [LLNL/lbann#127]
Getting number of neurons from data reader was a nice feature and save users the trouble of  specifying num of neurons for FC layer in autoencoder. However, it seems that if users replace this flexible approach by specifying the number of neurons, LBANN fails with the message below, I think that a user should be able to specify number of neurons in any layer if s/he chooses to.

[libprotobuf ERROR google/protobuf/text_format.cc:299] Error parsing text-format lbann_data.LbannPB: 289:16: Message type "lbann_data.Layer" has no field named "num_neurons".

**Comment by davidHysom** [comment]
While "num_neurons" has been removed as a field from Layer, there is a "num_neurons" filed in  FullyConnected. Are there any other Layer types for which it's useful to explicitly specify num_neurons?

**Comment by samadejacobs** [comment]
If I replace num_neurons_from_data_reader: true with num_neurons: 1023 on line  269 of this model zoo file ([link](https://github.com/LLNL/lbann/blob/develop/model_zoo/models/autoencoder_candle_pilot1/model_autoencoder_chem_ecfp.prototext)), I get the error message: [libprotobuf ERROR google/protobuf/text_format.cc:299] Error parsing text-format lbann_data.LbannPB: 289:16: Message type "lbann_data.Layer" has no field named "num_neurons"

**Comment by ndryden** [comment]
The `num_neurons` field goes inside the `fully_connected` message, not the `Layer` message. See e.g. [here](https://github.com/LLNL/lbann/blob/develop/model_zoo/models/alexnet/model_alexnet.prototext#L259).

**Comment by samadejacobs** [comment]
Thanks Nikoli, closing!
