### ISSUE TITLE
Better checking of command line arguments

### ISSUE THREAD

**Issue by bvanessen** [LLNL/lbann#138]
We need some better checking of command line arguments.  today, I was able to use --model=... --data_reader=... --optimizer=...

The error is that I should have had --reader=...

The model failed to find the data reader and gave an error that the size of the input layer was zero.  We should have checked for a valid triple of command line arguments, or thrown an error that the data_reader object was null.

**Comment by davidHysom** [comment]
currently model_zoo/lbann throws an exception if options doesn't contain either (1) model, or (2) loadme. Note that 'loadme' is for rerunning a previous experiment, in which case there is a single prototext file that contains the model, reader, and optimizer. So, we don't want to insist the command line contains a triple. Instead, I'll put a check in model_zoo/lbann to ensure all three parts are present in the parsed prototext.

**Comment by bvanessen** [comment]
That sounds good.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by davidHysom** [comment]
lbann and lbann2 now both call utils/load_prototext(), which checks for ill formed command line parameters, and verifies that the loaded protobuf structures contain a model, reader, and optimizer.
Also added some unit tests, which you can run locally in the bamboo/unit_tests directory via:
python -m pytest --exe=../../build/catalyst.llnl.gov/model_zoo/lbann -s test_lbann_invocation.py
