### ISSUE TITLE
Errors compiling Elemental with Intel compiler

### ISSUE THREAD

**Issue by timmoon10** [LLNL/lbann#14]
There is a longstanding issue with compiling Elemental under the Intel compiler (https://github.com/elemental/Elemental/issues/177). I recommend building LBANN with GCC until that bug is fixed, especially if you are building Elemental with the CMake build system.

**Comment by ndryden** [comment]
It looks like this issue is resolved in Intel 17.0.1. Note this is not yet present on the LC systems. I can't tell whether this will be resolved in a later release of Intel 16.

**Comment by ndryden** [comment]
Building with Intel 17.0.2 on catalyst, I now get the following error in building OpenBLAS inside of Elemental:
```
/usr/tce/packages/intel/intel-17.0.2/bin/icc -c -O2 -DMAX_STACK_ALLOC=2048 -wd981 -openmp -DF_INTERFACE_INTEL -fPIC -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=48 -DASMNAME=dtrsm_olnucopy -DASMFNAME=dtrsm_olnucopy_ -DNAME=dtrsm_olnucopy_ -DCNAME=dtrsm_olnucopy -DCHAR_NAME=\"dtrsm_olnucopy_\" -DCHAR_CNAME=\"dtrsm_olnucopy\" -DNO_AFFINITY -I.. -DDOUBLE  -UCOMPLEX  -DDOUBLE -UCOMPLEX -DOUTER -DLOWER -DUNIT generic/trsm_lncopy_4.c -o dtrsm_olnucopy.o
../kernel/x86_64/dscal.c(96): catastrophic error: unknown register name "%2" in asm statement

compilation aborted for ../kernel/x86_64/dscal.c (code 4)
gmake[7]: *** [dscal_k.o] Error 4
```

**Comment by ndryden** [comment]
I tried Intel 17.0.2 with the latest development version of OpenBLAS and it builds fine on its own.

However, Elemental still does not build, failing with the same error as in 17.0.1.

**Comment by ndryden** [comment]
@bvanessen Didn't you get this working in the Spack build?
