### ISSUE TITLE
LBANN build issue with libopencv_imgcodecs.so.4.2.0

### ISSUE THREAD

**Issue by sheltongeosx** [LLNL/lbann#1434]
Dear Developers:

I am using CMake to build LBANN in which opencv is required. With opencv compiled with libz-1.2.9, LBANN show error: 

     libopencv_imgcodecs.so.4.2.0: undefined reference to `inflateValidate@ZLIB_1.2.9'

But with opencv compiled with libz-1.2.7, it give the error: 
   

     libopencv_imgcodecs.so.4.2.0: undefined reference to `inflateValidate'

By greping "inflateValidate" from libz.a(.so also) it has the simbol.

Thanks for any advice on this!

Best,
Shelton

**Comment by benson31** [comment]
This sounds like a bug in OpenCV. If it was built with zlib support, it should have exported that dependency and include logic for finding it in its CMake export (e.g., `/path/to/opencv/lib64/cmake/opencv4/OpenCV*.cmake`) -- large, modern packages cannot possibly expect to keep up with the dependency graph beyond "first-order dependencies" (OpenCV, in this case); hence CMake package exports. I recommend filing a bug with the OpenCV folks.

In the meantime, you can make a quick addition to the main LBANN `CMakeLists.txt` to patch this:
```cpp
-target_link_libraries(lbann PUBLIC ${DL_LIBRARY})
+target_link_libraries(lbann PUBLIC ${DL_LIBRARY} /path/to/my/libz.so)
```
This will add libz to the linker line for LBANN so this symbol will be found.

Hope this helps.

**Comment by sheltongeosx** [comment]
Thank you very much @benson31 for your reply!

I added the the line to the CMakeLists.txt. But running cmake it still stick to the system zlib: 
    
    -- Found Hydrogen: ... .../Elemental/build
    -- Found ZLIB:  /usr/lib64/libz.so (found version "1.2.7") 
    -- Found Protobuf: ... .../protobuf/cmake/build/lib64/cmake/protobuf
But it did gives a lot of following warnings:
 
      runtime library [libz.so.1] in /usr/lib64 may be hidden by files in:
      ... .../zlib-1.2.11/build/lib
      Some of these libraries may not be found correctly.
 From the generated cmake results it uses /usr/lib64/libz.so everywhere. Is there any way to force  cmake stop using system libz? Thanks!

**Comment by benson31** [comment]
Ah, ok. It looks like Protobuf is actually using ZLIB, too. In this case, start from a clean build directory (remove, at a minimum, `CMakeCache.txt` and `CMakeFiles/`). Then, when configuring LBANN, add the custom ZLIB install prefix to the CMAKE_PREFIX_PATH environment variable:
```
CMAKE_PREFIX_PATH=/path/to/zlib/prefix:$CMAKE_PREFIX_PATH cmake ...
```
This method of controlling CMake's `find_package` behavior is discussed in the [CMake documentation](https://cmake.org/cmake/help/v3.14/command/find_package.html).

If this is unsuccessful, Protobuf will use [CMake's FindZLIB module](https://cmake.org/cmake/help/v3.14/module/FindZLIB.html), so you can always set `ZLIB_INCLUDE_DIRS` and `ZLIB_LIBRARIES` manually to force it to use whatever you want.

**Comment by bvanessen** [comment]
Shelton,  

Challenges about multiple versions of dependent libraries is one of the reasons that we use spack to install dependencies.  It provides a comprehensive way to make sure that all of the dependencies are built in a consistent fashion and shared between the different packages.

**Comment by sheltongeosx** [comment]
@benson31 Tom, 
Cool! It works beautifully with which I have successfully built LBANN (with all its needed dependencies) using cmake.

@bvanessen Brian,
Yeah, we are going to begin the test for spack locally for possible deployment to our system. Thank you Brian.   

Best,
Shelton
