### ISSUE TITLE
Another issue with the Siamese

### ISSUE THREAD

**Issue by JaeseungYeom** [LLNL/lbann#145]
I am experimenting with the DAG-based Siamese model until the weight sharing issue is resolved.
However, I think I might have discovered another potential issue. When I change the size description of the input in the prototext, I get error as below:
"src/weights/fan_in_fan_out_initializers.cpp 69 :: invalid dimensions for He normal initialization (fan_in=0,fan_out=4096)" 

Basically, what I do is scaling the image size to a quarter by changing the width and the height from 512 to 256. Then, I change the patch sizes from 96 to 48, the gap size from 48 to 24, and the jitter size from 7 to 4.
In this way, I can reuse the pre-cropped image for Alexnet for quick testing. This ran before weight refactoring. However, it no longer runs. Am I missing something?

**Comment by timmoon10** [comment]
If we run the default Siamese model, we see that conv5 has output dimensions 256x4x4. This is passed through pool3, which is a 3x3 max pool with output dimensions 256x1x1. If we halve the patch size, conv5 will have output dimensions 256x2x2 and pool3 will not have any output. I think your error is coming in fc6 when it sees its input dimensions are zero. This seems like correct behavior.

This case makes me think we need a pooling layer that can conveniently accommodate arbitrary input dimensions. I've run into this problem before with Resnet-50, which has an average pooling layer before the output.

**Comment by JaeseungYeom** [comment]
I see. It is absolutely better that now such an error is detected.
However, the error message is not so intuitive, because it sounds like coming from the concatenation layer that follows fc6 while it is at the input of fc6.

**Comment by timmoon10** [comment]
Perhaps we should make any layer with zero output throw an error.

**Comment by bvanessen** [comment]
Yes, that sounds good.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470
