### ISSUE TITLE
Lbann cmake build issue

### ISSUE THREAD

**Issue by sheltongeosx** [LLNL/lbann#1453]
Dear All,

I am using CMake to build LBANN on IBM power8. At the last step to compile lbann, after successful cmake and make, the 'make install' command seems to recompile the source code again from the beginning which had been compiled already in 'make' stage. It took quite long time to reach to about 33% and jump to 93% and continue compiling to the finish. Is it the way it supposes to be?

Thanks,
Shelton

**Comment by benson31** [comment]
This shouldn't happen, but sometimes wires get crossed especially if there are any remnants of any previous builds. I'm not as familiar with dependency tracking in the makefile generator as I am with the ninja generator. If you start from a completely clean build directory (remove any hidden directory or files, too, or just start from a brand new directory) and continue to observe this, please let us know.

**Comment by benson31** [comment]
@sheltongeosx Is this still happening?

**Comment by sheltongeosx** [comment]
Not sure yet - currently I am working on X86 machines. I will update this when I get change...

**Comment by sheltongeosx** [comment]
It look that the issue is gone. Thanks.
