### ISSUE TITLE
Metrics is broken

### ISSUE THREAD

**Issue by samadejacobs** [LLNL/lbann#148]
A test experiment using CANDLE P1 benchmark

@commit ee560028f66781333b7383afcb25eb689c298888

[1] Epoch : stats formated [tr/v/te] iter/epoch = [10311/1146/1273]
            global MB = [ 128/ 128/ 128] global last MB = [  38/  75/ 113]
             local MB = [ 128/ 128/ 128]  local last MB = [  38/  75/ 113]
--------------------------------------------------------------------------------

Model 0 training epoch 1 objective function : 0.0311647
**Model 0 training epoch 1 pearson correlation metric : 0.579729**
Model 0 training epoch 1 run time : 206.221s

@current develop
--------------------------------------------------------------------------------

[1] Epoch : stats formated [tr/v/te] iter/epoch = [10311/1146/1273]

            global MB = [ 128/ 128/ 128] global last MB = [  38/  75/ 113]

             local MB = [ 128/ 128/ 128]  local last MB = [  38/  75/ 113]

--------------------------------------------------------------------------------
Model 0 training epoch 1 objective function : 0.0311647

**Model 0 training epoch 1 Pearson correlation : 0.00452944**

Model 0 training epoch 1 run time : 205.835s

**Comment by davidHysom** [comment]
Can you be more verbose? Apparently "Model 0 training epoch 1 pearson correlation metric : 0.579729" is the symptom. What value(s) do you expect, and where did those values come from?

**Comment by timmoon10** [comment]
I think this is fixed in 9035079611438611c059577e2ab389f6ddcd2939. When I run with a convolution autoencoder on MNIST, I get a Pearson correlation above 0.8. The reconstructions look good visually, so this seems reasonable.
