### ISSUE TITLE
Cleaning up legacy prototext models

### ISSUE THREAD

**Issue by bvanessen** [LLNL/lbann#1495]
autoencoder_candle_pilot1
- [ ] model_autoencoder_chem_ecfp.prototext
- [x] model_autoencoder_chem_ecfp_200x150x100x100x100.prototext
- [x] model_autoencoder_chem_ecfp_500x250x100.prototext
- [x] model_autoencoder_chem_sigmoid.prototext
- [ ] model_dnn_chem_ecfp.prototext

autoencoder_cifar10
- [x] model_autoencoder_cifar10.prototext
- [x] model_conv_autoencoder_cifar10.prototext

autoencoder_imagenet
- [x] model_conv_autoencoder_imagenet.prototext

autoencoder_mnist
- [x] model_autoencoder_mnist.prototext
- [x] model_conv_autoencoder_mnist.prototext
- [ ] vae_mnist.prototext

candle/pilot1
- [ ] ae_nodeselect_gdc.prototext
- [ ] combo.prototext

cosmoflow
- [x] ae_nodeselect_gdc.prototext

gan
- [x] jags/cycle_gan
- [ ] mnist

jag
- [x] ae_cycle_gan
- [x] gan
- [x] wae_cycle_gan
- [x] vae_fcn.prototext
- [x] wae.prototext

molecular_autoencoder_candle_pilot2
- [ ] model_conv_molecular_autoencoder_pilot2.prototext
- [ ] model_conv_molecular_bead_autoencoder_pilot2.prototext
- [ ] model_molecular_autoencoder_pilot2.prototext

siamese
- [x] finetune-cub
- [x] triplet

simple_mnist
- [x] model_mnist_simple_1.prototext
- [x] model_mnist_simple_2.prototext

**Comment by davidHysom** [comment]
Simple_minst models should go away; Katie previously notified

**Comment by bvanessen** [comment]
Closed by #1526 .
