### ISSUE TITLE
Better pointer handling

### ISSUE THREAD

**Issue by timmoon10** [LLNL/lbann#155]
As our code becomes increasingly complicated, I think better pointer management would be good for robustness and simplification. I propose the following changes:
- [x] Layers maintain input and output matrices in vectors of `unique_ptr`s (see #153).
- [ ] Elemental matrices are stored in `unique_ptr`s whenever possible.
- [x] Models maintain layers in a vector of `unique_ptr`s.
- [x] Models maintain weights in a vector of `unique_ptr`s
- [ ] Models maintain metrics in a vector of `unique_ptr`s.
- [x] Models maintain callbacks in a vector of `unique_ptr`s.
- [x] Models maintain objective function in a `unique_ptr`.
- [x] Models maintain default optimizer in a `shared_ptr`.
- [x] Objective functions maintain terms in a vector of `unique_ptr`s.
- [x] Weights maintain optimizer in a `unique_ptr`.
- [x] Refactor GPU support so that layers no longer need to maintain a reference to a cudnn_manager object. Instead, we should create a `cuda` namespace with globally accessible functions. This may become moot with Hydrogen (@benson31).
- [ ] We should prefer function arguments that are references rather than pointers.

**Comment by ndryden** [comment]
I think this would be quite helpful for thinking about what objects own what data, who is responsible for freeing it, etc.

If we do this, we should probably also switch to using `std::make_shared` and `std::make_unique`. (The latter might be slightly troublesome with some pedantic compilers, because the committee accidentally left it out of C++11, so it's only officially present in C++14.)

**Comment by benson31** [comment]
```cpp
#include <memory>
namespace lbann
{

template <typename T>
using MakeShared = std::make_shared<T>;

#if __cplusplus < 201402L

template <typename T, typename... Ts>
std::unique_ptr<T> MakeUnique(Ts&&... params)
{
    return std::unique_ptr<T>(new T(std::forward<Ts>(params)...));
}

#else

template <typename T>
using MakeUnique = std::make_unique<T>;

#endif
```
You could also keep things in the `make_shared` or `make_unique` format if you prefer the STL look and feel (I usually do, but I've been reading a lot of Elemental lately).

Real `std::make_unique` handles a few other cases that we could add if needed (e.g., `T[]`), but for me, this has covered the 99% use case.

**Comment by benson31** [comment]
```cpp
}// namespace lbann
```
Oops.

**Comment by timmoon10** [comment]
We should think about smart pointer semantics. In my mind, a `unique_ptr` implies an ownership relationship and a `shared_ptr` implies that an object is self-sufficient. Raw pointers indicate a weak reference and they should not be stored longer than needed. However, this is a little weird since smart pointers were designed to avoid passing around raw pointers at all.

Perhaps we can use an alternate mental model. A `shared_ptr` can either represent an independent object or an ownership relationship where other objects occasionally have access. For instance, the weights class can keep an optimizer in a `shared_ptr` and can pass `weak_ptr`s to layers for backprop gradient updates. This approach has the advantage of avoiding raw pointers. However, it also makes ownership relationships less clear.
