### ISSUE TITLE
Code availability of channel and filter-wise parallelism 

### ISSUE THREAD

**Issue by ved27** [LLNL/lbann#1586]
Hi,

I wish to experiment channel/filter-wise parallelism;
Is it publicly available yet? If so, can you please direct me to its documentation?

Thank you!

**Comment by timmoon10** [comment]
The distributed convolution work is available, although it's still in a messy, experimental state.

### Build instructions

Dependencies:
- [Aluminum](https://github.com/LLNL/Aluminum), built with the `-DALUMINUM_ENABLE_MPI_CUDA=ON` CMake flag. 
- [DiHydrogen](https://github.com/llnl/dihydrogen).
- CUDA

LBANN itself must be built with the `-DLBANN_WITH_DISTCONV=ON` CMake flag. See the documentation for building LBANN at https://lbann.readthedocs.io/en/latest/build_with_cmake.html.

Pinging @benson31.

### Run instructions

The documentation for running vanilla data-parallel LBANN is at https://lbann.readthedocs.io/en/latest/running_lbann.html#python-frontend. [The reference LeNet implementation](https://github.com/LLNL/lbann/blob/develop/applications/vision/lenet.py) is a good example.

To enable advanced data distributions, you need to pass a `dict` as the `parallel_strategy` for each layer. Something like:
```python
y = lbann.Convolution(
    x,
    num_dims = 2,
    num_output_channels = 123,
    conv_dims_i = 3,
    conv_strides_i = 1,
    has_bias = True,
    parallel_strategy = {"channel_groups" : 4, "filter_groups" : 4},
)
```
The list of options is at https://github.com/LLNL/lbann/blob/ead1dd95851edeb403264b18dd613ac976853398/src/proto/layers.proto#L778.

Pinging @oyamay and @samadejacobs.

**Comment by ndryden** [comment]
The stationary-x version of channel/filter parallelism is public (see [here](https://github.com/LLNL/DiHydrogen/tree/master/legacy)), but has not made it into the main LBANN branch. The stationary-y and -w algorithms are not yet in that release.

**Comment by ved27** [comment]
So as @timmoon10  mentioned that distributed conv wonk is available, I hope all stationary -x,-y,-w are available to run, but only code of stationary -x is public?
