### ISSUE TITLE
Comparing LBANN and mesh-tensorflow   

### ISSUE THREAD

**Issue by ved27** [LLNL/lbann#1587]
Hi,

I wish to compare LBANN and mesh-tensorflow, especially their methodologies in 
implementing model-parallelism. 
Can you please provide a direction or is there any resource that does the comparison ? 

Thank you!

**Comment by ndryden** [comment]
Can you be more specific about what you want to compare? For the key ideas behind the implementations, I recommend going through some of the [LBANN papers](https://lbann.readthedocs.io/en/latest/publications.html).

**Comment by ved27** [comment]
Hi, 

I actually went through the papers
I wish to know about some benchmarking results of any single model implemented using LBANN compared to the results of the same model implemented in mesh-tensorflow and executed using the similar resources. 

For example: 
Resnet  50 using spatial partitioning - model parallelism : mesh-tensorflow vs LBANN results

Can you please let me know if any such comparison exists?

**Comment by ndryden** [comment]
We have not run any comparisons like that, and I'm not sure they exist. The spatial partitioning code is supported in the main LBANN repo, so this should be runable.

**Comment by ved27** [comment]
Thank you for the info. I wish to know if we can run large 3D models on GPUs using spatial partitioning of LBANN. Are there any tried examples?

**Comment by ndryden** [comment]
There's not much in terms of documentation of examples. I would take a look at Tim's response [here](https://github.com/LLNL/lbann/issues/1586#issuecomment-658501779).

**Comment by ved27** [comment]
Thanks @ndryden ,
