### ISSUE TITLE
Signed/unsigned comparisons

### ISSUE THREAD

**Issue by ndryden** [LLNL/lbann#2]
We have a lot of signed/unsigned comparison warnings that show up. We should fix them all.

A decent number seem to be from using unsigned loop iteration variables, and comparing them to signed upper bounds, e.g. the width of an Elemental matrix. Since Elemental (and MPI) use signed ints, we should probably use them in such cases.

**Comment by timmoon10** [comment]
I don't see any more complaints about this when I compile with GCC and -Wall. I think we got 'em all.
