### ISSUE TITLE
All LBANN functionality should be in lbann namespace

### ISSUE THREAD

**Issue by timmoon10** [LLNL/lbann#204]
If we want other projects to call LBANN as a library (#199), we should take care to avoid naming conflicts. Some of our typedefs and enums in include/lbann/base.hpp are defined in global scope and have common names like `Mat` or `Grid`. This should be easy to fix, but it will probably require squashing many compilation errors.

**Comment by ndryden** [comment]
Just want to add that absolutely no header file should have `using namespace ...` in it (otherwise you pollute other projects and namespaces). I think I squashed all of them, but I thought I'd mention it just in case they creeped in again.
