### ISSUE TITLE
proposal to remove generic_data_reader::swap_role()

### ISSUE THREAD

**Issue by JaeseungYeom** [LLNL/lbann#207]
I don't think we need this function.
The only place we use it is in the src/proto/proto_common.cpp
It is followed by use_unused_index_set(). We can change it to set_role().

The function does not make sense to me because `m_use_percent` and `m_validation_percent` are not compatible. In addition, `use_unused_index_set()` does not preserve the swapped indices anyway. `m_use_percent`, `m_validation_percent`, and `m_absolute_sample_count` should only be used in `select_subset_of_data()` once, and should not be used beyond that point. We can query the number of samples maintained by a reader by `get_num_data()`

**Comment by davidHysom** [comment]
agree

**Comment by JaeseungYeom** [comment]
I will create PR tomorrow if there is no objection until then.
