### ISSUE TITLE
CSV reader fails to load Pilot1 data

### ISSUE THREAD

**Issue by timmoon10** [LLNL/lbann#211]
When I run an experiment with the Pilot1 data, I get the following error:

```
**************************************************************************
 This lbann_exception is about to be thrown:csv_reader: failed to open chem.P1B3_test_drugs.txt.train.X.1

 Am now attempting to print the stack trace ...
**************************************************************************
rank: 0 :: rank: 0 :: rank: 0 :: lbann::csv_reader::setup_ifstreams()
rank: 0 :: lbann::csv_reader::load()
rank: 0 :: init_data_readers(bool, lbann_data::LbannPB const&, std::map<execution_mode, lbann::generic_data_reader*,\
 std::less<execution_mode>, std::allocator<std::pair<execution_mode const, lbann::generic_data_reader*> > >&)
rank: 0 :: dli_sname == NULL for: 0x403bea backtrace message was: /g/g17/moon13/src/lbann/build/gnu.catalyst.llnl.go\
v/lbann/build/model_zoo/lbann() [0x403bea]
rank: 0 :: demangling failed for: __libc_start_main
rank: 0 :: dli_sname == NULL for: 0x40472e backtrace message was: /g/g17/moon13/src/lbann/build/gnu.catalyst.llnl.go\
v/lbann/build/model_zoo/lbann() [0x40472e]
```

This error does not appear in fd17b8811dc1b8ed3d40befae70b8f0d5592a129. I see that line 337 in data_reader_csv.cpp has been changed to load from `get_file_dir()+ get_data_filename()`. I suspect `get_file_dir()` is not behaving as expected.

**Comment by JaeseungYeom** [comment]
Can you try `add_delimiter(get_file_dir()) + get_data_filename()`. This could just be the path delimiter missing at the end in the prototext.

**Comment by bvanessen** [comment]
Which system are you running on and is it pointing at the correct location on parallel file system.  I don't believe that this is a path delimiter issue, I tried to specifically address that.

**Comment by timmoon10** [comment]
I ran it on Catalyst and I just used the path in data_reader_candle_pilot1.prototext. I see that that was changed recently too, so maybe there's a bug in the prototext parsing?

**Comment by bvanessen** [comment]
Hmmm, I will look at it shortly.


Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by bvanessen** [comment]
bash-4.2$ srun ./build/gnu.Release.catalyst.llnl.gov/lbann/build/model_zoo/lbann --model=model_zoo/models/autoencoder_candle_pilot1/pilot1b3_snn_autoencoder.prototext --reader=model_zoo/data_readers/data_reader_candle_pilot1.prototext --optimizer=model_zoo/optimizers/opt_adam.prototext --mini_batch_size=1024 --procs_per_model=0  --num-epochs=1 --use_cudnn=0     

Works fine for me.

**Comment by bvanessen** [comment]
Can you please provide an exact command line for what you have run, when you get this failure.

**Comment by timmoon10** [comment]
I'm not seeing this anymore, so I'll close the issue.

For the sake of history, I got the error with the following command:
```
srun --nodes=1 --ntasks=1 /g/g17/moon13/src/lbann/build/gnu.catalyst.llnl.gov/lbann/build/model_zoo/lbann --model=/g/g17/moon13/src/lbann/model_zoo/models/autoencoder_candle_pilot1/model_autoencoder_modelparallel_100.prototext --num_epochs=10 --optimizer=/g/g17/moon13/src/lbann/model_zoo/optimizers/opt_sgd.prototext --reader=/g/g17/moon13/src/lbann/model_zoo/data_readers/data_reader_candle_pilot1.prototext
```
