### ISSUE TITLE
Update Allreduce support in LBANN build system

### ISSUE THREAD

**Issue by benson31** [LLNL/lbann#216]
Since I wrote a complete CMake build system (i.e., including functioning CMake export) for the all-reduce library, FindALUMINUM.cmake should change. Namely, it should be a wrapper around a call to ```find_package(Aluminum)```, which should go find AluminumConfig.cmake, which is installed by Aluminum and will import the library target (called ```AL::Aluminum```). The wrapper should do some checking to make sure compatible MPI/CUDA/NCCL ducks are all neatly aligned in a row, and then return. Then, just link to AL::Aluminum and we should be all good.

I intend to do all this myself; leaving this here as a TODO for me to take care of in between Hydrogen builds...

**Comment by ndryden** [comment]
This is done.
