### ISSUE TITLE
Using GCC Address Sanitizer to check for memory errors

### ISSUE THREAD

**Issue by bvanessen** [LLNL/lbann#22]
It would be nice to see if we can use features such as the GNU GCC AddressSanitizer described at https://gcc.gnu.org/gcc-4.8/changes.html to help improve the robustness of the code.

**Comment by davidHysom** [comment]
With a bit of hacking I was able to compile with Clang and Asan (Address Sanitizer):
modified scripts/build_lbann_lc.sh
  #CMAKE_C_COMPILER=${GNU_DIR}/gcc
  #CMAKE_CXX_COMPILER=${GNU_DIR}/g++
  CMAKE_CXX_COMPILER=/usr/global/tools/clang/chaos_5_x86_64_ib/clang-3.8.0/bin/clang++
  CMAKE_C_COMPILER=/usr/global/tools/clang/chaos_5_x86_64_ib/clang-3.8.0/bin/clang

modified CMakeLists.txt:
set(CMAKE_CXX_FLAGS "-fsanitize=address -fno-omit-frame-pointer -fsanitize-recover=address ${CMAKE_CXX_FLAGS} -fPIC -std=c++11")
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -O1")

$ use clang-3.8.0 #not sure if this is necessary
$ ../scripts/build_lbann_lc.sh --verbose --debug

Before running an LBANN driver:
$ setenv ASAN_OPTIONS halt_on_error=0
Note: without this setting, asan will exit when it encounters an error; with this setting is will continue

**Comment by davidHysom** [comment]
clang's address sanitizer is used if you build with --compiler clang
