### ISSUE TITLE
saving and loading weights

### ISSUE THREAD

**Issue by JaeseungYeom** [LLNL/lbann#225]
I need a subset of CR capability as my workflow does not require the states of random number generators, input layers, or data readers. What I need is to save weights at the end of training, and load them into a new model.

Currently, I am using lbann2 to train a model and copy the weights of some of the layers to the corresponding ones in another model. Currently, the first model has to run whenever I want to run the second one.

However, I wish to keep these weights and reuse them in multiple experiments to try various types of second models instead of repeatedly rerunning the first model. 

Unless we already have such as capability, can it be easily integrated into lbann2?

**Comment by davidHysom** [comment]
Looks like something like this should work to save the weights:

lbann::persist p;
p.open_checkpoint(dir, per_rank); //don't know what 'per_rank' means, as it's undocumented

const auto layers1 = model_1->get_layers();
for (auto t : layers1) {
  const std::vector<weights *> w = layers1->get_weights();
  w.save_to_checkpoint_shared(p);
}

Something similar should work for loading the weights

________________________________

**Comment by JaeseungYeom** [comment]
Thanks a lot. This look simple enough.
I guess I can have a prototext flag such as save_weights, and a similar one for loading.
If anyone can work on this, feel free to assign yourself.

**Comment by DylanMcKinney** [comment]
I am currently testing an implementation of this. It appears to be working, or close to. [Branch](https://github.com/DylanMcKinney/lbann/tree/lbann2_ckpt) in case anyone wants to look over this. I will PR shortly.

**Comment by JaeseungYeom** [comment]
This has been completed.
