### ISSUE TITLE
Build Issue On Lassen

### ISSUE THREAD

**Issue by pate7** [LLNL/lbann#2276]
Howdy LBANN Team!

I'm trying to build LBANN on Lassen using the Spack environment procedure described on your read the docs page. I'm finding the following error:

```
==> Error: The "packages" section of the configuration needs to be written to disk, but is currently using a deprecated format. Please update it using:

	spack config [--scope=<scope>] update packages

Note that previous versions of Spack will not be able to use the updated configuration.
FAILED: spack config add packages:all:variants:'+cuda cuda_arch=70'
```

I ran the spack config command the error message suggested, but that did not resolve the issue. Do y'all have any suggestions on how to resolve this issue?

Joey

**Comment by fiedorowicz1** [comment]
Hi Joey,

A recent Spack update is causing this issue in our build script. To get you unstuck until we update the build script, you can add the following line right before [this one](https://github.com/LLNL/lbann/blob/f4f1130e1a08d0083c1c1b4623a711e3e12c4409/scripts/build_lbann.sh#LL706C3-L706C3):
`spack config update packages -y`

Hopefully that helps! Either way, we can leave this issue open until this is fixed.

-Pier

**Comment by pate7** [comment]
Okay. Thank you! I'll give that a shot. 

How do I start the build after modifying 'build_lbann.sh'? Activate the spack environment then rerun the 'build_lbann.sh' script?

**Comment by pate7** [comment]
That took the build further, but now 'nccl' is failing to build through spack. Have y'all seen that error before?

**Comment by benson31** [comment]
yeah, NVIDIA/nccl#835 is the root cause of that. Short of convincing LC to install modern compilers on the system, the best fix is to just force NCCL to build at a lower version. For the LBANN build script, add `^nccl@2.16.2-1` to the end of the spec you pass to the build script.

**Comment by pate7** [comment]
Haha. The compilers strike again. Thanks a ton!

**Comment by pate7** [comment]
Thanks again for the help y'all! I got things up and running on lassen. Closing the issue.

**Comment by ndryden** [comment]
@pate7 Great! Just an FYI, NCCL 1.18.3 was recently released, which fixes this. Not sure if Spack has it yet.

**Comment by pate7** [comment]
Cool. I may take a look at that. Thanks for the heads up! 

BTW, spack only has up to version 0.102 of LBANN available. I'm not sure if this is the place to raise that issue or if we need to wait for spack to catch up to v0.103
