### ISSUE TITLE
Ensure GPU convolution buffers are sized appropriately

### ISSUE THREAD

**Issue by ndryden** [LLNL/lbann#231]
There appears to be a difference in convention in how our CPU convolution implementation and cuDNN place convolution filters on the images that are being convolved. We should ensure that we correctly calculate the size of the GPU buffer to ensure there are no off-by-one (or similar) errors.

As far as I know, this hasn't impacted any of our results yet, but it would be good to ensure it's never an issue.

The `cudnnGetConvolution2dForwardOutputDim` method may be helpful here.

(I've discussed this with Tim in more detail over the phone.)

**Comment by timmoon10** [comment]
I think it turned out that this wasn't an issue, so I'll close it.

Pinging @naoyam just in case.

**Comment by naoyam** [comment]
Sounds good to me.
