### ISSUE TITLE
Performance tuning / minimizing data transfer overhead for GPU support of convolutional networks

### ISSUE THREAD

**Issue by bvanessen** [LLNL/lbann#24]
Reduce the time per forward pass step when offloading convolutional / pooling operations to GPUs.  Identify where the excess time is being spent.  Investigate if using pinned memory allocations will allow for more efficient GPU asynchronous data transfer.  Look at leaving filter weights on the GPU and overwriting on the next iteration.

**Comment by timmoon10** [comment]
As of b84e709e0280f6a2c053cd00d2486e25efd5a7ca, data is kept resident on GPU when adjacent layers are on GPU. GPU memory transfers are performed with pinned memory.
