### ISSUE TITLE
strange behavior with fully connected layers in data parallel mode on ray 

### ISSUE THREAD

**Issue by JaeseungYeom** [LLNL/lbann#265]
The large fully connected layers in data parallel mode on ray shows 'nan' for objective function value.
This does not happen on surface.

**Comment by ndryden** [comment]
Can you be more specific? What model? How many nodes? etc.

**Comment by samadejacobs** [comment]
I have been training "large" fully connected layers in data parallel mode on ray (up to 8 nodes, 32GPUs) and the results seem reasonable/comparable to what I got on Catalyst. I am using MSE as objective function. My code is as up-to-date as early this week.

**Comment by JaeseungYeom** [comment]
I was using Siamese model, and 8 nodes with 4 gpus/node.
The mini batch size is 128 samples.
There are four FC layers. Especially, the second and third ones are larger than the others.
The second one has the input size 12288, and the output size 4096.
The third one has the input size 4096, and the output size 4096.
When I convert the data layout of either of the two FC layers, the objective function value becomes 'nan'.

**Comment by JaeseungYeom** [comment]
This issue has been resolved now.
