### ISSUE TITLE
Optimize performance of CPU-based convolution layers

### ISSUE THREAD

**Issue by bvanessen** [LLNL/lbann#29]
Currently CPU-based convolution uses a simple, straight-forward algorithm.  This should be reimplemented to provide better performance and leverage CPU vector units.

**Comment by timmoon10** [comment]
The current algorithm explicitly constructs the convolution matrix on each process and performs a matrix multiplication. Profiling with VTune finds that about 65% of the total run time is spent in GEMM calls. >16% of the run time is spent constructing the convolution matrix.

**Comment by timmoon10** [comment]
CPU convolution is implemented with an im2col GEMM algorithm as of 22866d9ccdc980191fd470bc35eb3c004c01fc1a. CPU runtime on AlexNet is now about 10x slower than GPU runtime.
