### ISSUE TITLE
Total GPU memory footprint

### ISSUE THREAD

**Issue by bvanessen** [LLNL/lbann#345]
Examine how big the footprint is and are there some easy optimizations if networks are not able to fit on systems that they should.

**Comment by timmoon10** [comment]
#356 should reduce GPU memory requirements by about half.

**Comment by timmoon10** [comment]
I've heard complaints that some models don't fit on GPU, even though they did in the past. I suspect that making the CUB memory pool the default GPU memory allocator (https://github.com/LLNL/Elemental/pull/14) increased our memory usage. One solution is to avoid the CUB memory pool for GPU matrices that are only allocated/deallocated once, e.g. layer input/output tensors and weights.

**Comment by ndryden** [comment]
Perhaps we can use #452 or something derived from it to identify where this is going wrong?
