### ISSUE TITLE
Refactor cuDNN manager

### ISSUE THREAD

**Issue by timmoon10** [LLNL/lbann#360]
Now that we support GPU Hydrogen (#250), much of the GPU functionality in LBANN is deprecated:
- GPU matrices.
- GPU memory allocation and movement routines.
- CPU memory pinning.
- Multiple GPUs per process.

In addition, #250 started templating layers by device type. Our old approach was to enable/disable the GPU implementation based on whether the layer had a null pointer to a cuDNN manager. We should clean up the code and commit to the template approach to minimize the risk of bugs.

**Comment by bvanessen** [comment]
I agree that we should use the Device type and get rid of the null pointer to cuDNN manager.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470
