### ISSUE TITLE
Summarizer should report objective function results

### ISSUE THREAD

**Issue by timmoon10** [LLNL/lbann#413]
The summarizer collects data from the communicator, layers, weights, and metrics. It would be useful if it also reported information about the objective function terms.

Related, the reconstruction layer collects objective function data for the summarizer (see #410). This functionality should be removed.

**Comment by ndryden** [comment]
What information are you thinking of? The current mean value of the objective function is logged in `model::summarize_stats` (along with runtimes).

**Comment by timmoon10** [comment]
In that case, we should be safe deleting the reconstruction layer.
