### ISSUE TITLE
OpenBLAS needs patching if using Intel compiler + superbuild

### ISSUE THREAD

**Issue by benson31** [LLNL/lbann#426]
OpenBLAS still thinks the OpenMP flag for Intel is "-openmp". There's a patch in spack that we should also apply in the superbuild.

**Comment by timmoon10** [comment]
Could be contribute this back to OpenBLAS?

**Comment by benson31** [comment]
Actually, OpenBLAS has fixed this already in `master`. Can we just tick up our OpenBLAS tag?

**Comment by JaeseungYeom** [comment]
need to clear up the deprecated patching scripts/files under extermal/OpenBLAS used before the superbuild.

**Comment by bvanessen** [comment]
I believe it is fine to use a newer version.


Brian C. Van Essen

vanessen1@llnl.gov<mailto:vanessen1@llnl.gov>

(w) 925-422-9300

(c) 925-290-5470

---

Sent from my iPhone

On Jun 14, 2018, at 9:04 AM, Tom Benson <notifications@github.com<mailto:notifications@github.com>> wrote:


Actually, OpenBLAS has fixed this already in master. Can we just tick up our OpenBLAS tag?
