### ISSUE TITLE
The future of prototext motifs

### ISSUE THREAD

**Issue by timmoon10** [LLNL/lbann#436]
Quoting a comment by @davidHysom in #400:

>> To clarify, for motif prototext is the usage to first use expandmotifs.py to generate a runnable prototext file from the motif prototext?
>
>Yes. However, expandmotifs.py is broken, due to changes in our build system. Longer answer: the script builds the python wrappers for protocal buffers -- and it expects the directory /build/.llnl.gov/bin/protoc to exist. Except it no longer does.
>
>At one point I was going to port expandmotifs.py to c++, but never finished that.
>
>I think we should discuss, perhaps at next Wed. mtg, if we want to maintain the motif functionality. If yes, it needs (perhaps considerable) repair.
>
>Additionally, model_resnet50_motif.prototext contains "split" layers, but currently model_resnet50.prototext does not -- so even if expandmotifs.py worked it would not output a runnable prototext model.

**Comment by timmoon10** [comment]
My thoughts:
- For very complex models, e.g. my VRAM work and @samadejacobs's cycleGAN stuff, it seems we are moving away from manually writing prototext files and toward using protobuf's python interface. This gives us a lot of flexibility, but we are also essentially writing a custom python interface for every project. I don't think this is a good long-term approach.
- Passing parameters into the current motif interface is a bit cumbersome. This is most annoying when a motif has many input or output layers, e.g. recurrence steps in an RNN.
- I still think a curated list of common motifs like LSTM cells or inception units would be very useful.

**Comment by DylanMcKinney** [comment]
I think between a generalized protobuf python solution and revamping motifs, I would favor the python solution. I know both Ryans have also been finding success using python to generate res/densenets

**Comment by forsyth2** [comment]
@DylanMcKinney Yeah, for DenseNet (#303) I have a Python script that generates prototext. It seems like it works pretty nicely. I already have it laid out by functions that are dense-net specific and ones that are more generic. So, this script could be applied to other models. If we do that, it might be a good idea to break out the generic/shared functions into another Python file.

**Comment by ndryden** [comment]
> This gives us a lot of flexibility, but we are also essentially writing a custom python interface for every project. I don't think this is a good long-term approach.

This is basically the approach used by every other deep learning framework.

**Comment by timmoon10** [comment]
The worry I have is that it makes practitioners have to learn yet another framework.  In the long-term, I think the best solution would be a Keras interface (#273) that supports 95% of the use-cases.
