### ISSUE TITLE
The ifdef check does not agree with the header in the callback_gpu_memory_usage.cpp file

### ISSUE THREAD

**Issue by koning** [LLNL/lbann#455]
The header does not define the function if LBANN_HAS_CUDA is not defined in the callback_gpu_memory_usage.cpp file.

https://github.com/LLNL/lbann/blob/4fc1e2fd04b020e99fd162400732012897983659/src/callbacks/callback_gpu_memory_usage.cpp#L34

**Comment by DylanMcKinney** [comment]
Fixed in #454
