### ISSUE TITLE
Can't access cmake if not in brain group

### ISSUE THREAD

**Issue by koning** [LLNL/lbann#456]
Can this be changed to module load cmake/3.9.2 to work on all toss3 machines?

https://github.com/LLNL/lbann/blob/50ef366012bc8d7ef428a1a97a9ac2115b2f49bc/scripts/build_lbann_lc.sh#L299

**Comment by ndryden** [comment]
@benson31 I think you put this there, can you look into it?

**Comment by DylanMcKinney** [comment]
This may have been me actually. I will change the build script to use cmake 3.9.2

**Comment by DylanMcKinney** [comment]
closing -- fixed with #483
