### ISSUE TITLE
Save and load layer weights in protobuf format

### ISSUE THREAD

**Issue by bvanessen** [LLNL/lbann#47]

**Comment by timmoon10** [comment]
@DylanMcKinney Is this handled by the checkpointing functionality?

**Comment by DylanMcKinney** [comment]
Checkpoint is not in protobuf format, but I believe Sam wrote support to save weights in protobuf as a separate callback, [save model](https://github.com/LLNL/lbann/blob/develop/src/callbacks/callback_save_model.cpp). We can probably close this issue
