### ISSUE TITLE
Support weighted cross-entroy

### ISSUE THREAD

**Issue by ndryden** [LLNL/lbann#480]
Cross-entropy and binary cross-entropy can take per-class weights to adjust the importance of errors on different classes. (For binary cross entropy, there is a single weight, not two weights.)

**Comment by timmoon10** [comment]
We currently have support for this, if you don't mind building a monstrous prototext: setup weights as constant layers, concatenate them together to get a weights vector, use the log and Hadamard layers to compute terms for each entry, and use a reduction layer to get the final value.

I would rather only implement and support C++ layers if they are very common or if they are performance bottlenecks.

**Comment by timmoon10** [comment]
This can be implemented with something like the following:
```
layer {
  parents: "prediction_scores"
  name: "cross_entropy_terms"
  log_softmax {}
}
layer {
  name: "cross_entropy_weights_layer"
  weights: "cross_entropy_weights"
  weights_layer {
    dims: "1000"
  }
}
weights {
  name: "cross_entropy_weights"
  value_initializer {
    values: "1.0 1.1 1.2 ..."
  }
  optimizer {} # Disable optimizer
}
layer {
  parents: "cross_entropy_terms cross_entropy_weights"
  name: "weighted_cross_entropy_terms"
  multiply {}
}
layer {
  parents: "weighted_cross_entropy_terms"
  name: "cross_entropy"
  reduction { mode: "sum" }
}
```
