### ISSUE TITLE
build script option for enabling Aluminum

### ISSUE THREAD

**Issue by JaeseungYeom** [LLNL/lbann#489]
Currently, to build with Aluminum, we need not only '--aluminum-with-nccl' or '--aluminum-with-mpi-cuda' but also '--with-aluminum'.
Unless this is intentional, '--with-aluminum' is redundant.

**Comment by benson31** [comment]
It is intentional that `--with-aluminum` is a separate option. However, `--aluminum-with-<backend>` should imply `--with-aluminum` if it isn't explicitly specified.

**Comment by JaeseungYeom** [comment]
I was not sure what is '--with-aluminum' for. I assumed that it was the left over from the old method.

**Comment by benson31** [comment]
It's my understanding that Aluminum has optimized CPU-only allreduces, and then if you add the MPI-CUDA or NCCL backend, you get GPU support. Therefore the `--with-aluminum` flag is valid in a CPU-only build, whereas the `--aluminum-with-<backend>` is used to enable GPU-friendly backends.

**Comment by ndryden** [comment]
That's correct. `--with-aluminum` builds Aluminum with only the MPIBackend, which is always present. `--aluminum-with-<backend>` enables other backends (currently, NCCLBackend and MPICUDABackend).

**Comment by benson31** [comment]
I just patched `build_lbann_lc.sh` to do the right thing if you give `--aluminum-with-<backend>` but not `--with-aluminum`.
