### ISSUE TITLE
Quantization optimization

### ISSUE THREAD

**Issue by ndryden** [LLNL/lbann#5]
I just merged a bunch of updates to `lbann_quantizer`, mostly optimization. Lots of stuff runs faster, but this is to track some notes and further work on it:
- ~~While these updates algorithms seem correct after an initial pass, I need to do more checking/testing to ensure correctness.~~
- ~~One-bit quantization is quite slow. Part of this is due to computing averages over the whole data-- sampling to approximate the average would probably work better (this is already done in `proportion_threshold_average`). The AdaGrad step is also pretty slow.~~
- ~~One-bit quantization currently also has an outstanding bug leading to memory corruption that I haven't fixed.~~
- Compression could do with some further optimization, it roughly doubles runtime.
- We have lots of opportunities for multi-threading things to improve performance further.

Some notes:
- Threshold quantization suffers from a problem where the error feedback means it starts rapidly sending large amounts of data because entries exceed the threshold. (Adaptive quantization does not suffer this problem.)
- Threshold quantization before error feedback messes things up, and adaptive quantization consistently, perform the same or faster than the vanilla MPI allreduce for large matrices.
- Compression requires delta coding with large matrices, or we try and encode position numbers like 33 million, which is terrible with Golomb-Rice encoding.

**Comment by ndryden** [comment]
Fixed the onebit quantization crash in b332680.

**Comment by ndryden** [comment]
Started multi-threading stuff with OpenMP. We don't quite get linear speedup, but the speedup is okay (~2.5x with four threads for adaptive quantization). This did require some significant changes to how adaptive quantization laid out its data, in order to enable easy multi-threading of unquantization.

This broke compression, but probably provides a good opportunity to re-engineer/optimize it anyway.

**Comment by bvanessen** [comment]
Very cool.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by ndryden** [comment]
Quantization is pretty well optimized at this point. I think this can be closed and particular issues opened as-needed.
