### ISSUE TITLE
build broken

### ISSUE THREAD

**Issue by JaeseungYeom** [LLNL/lbann#504]
Currently, I am getting compilation error as below on surface:
.../lbann/build/gnu.Release.surface.llnl.gov/aluminum/src/test/test_nccl_collectives.cpp:251:74:   required from 'void test_bcast_algo(const typename VectorType<Backend>::type&, typename VectorType<Backend>::type, typename Backend::comm_type&, typename Backend::algo_type) [with Backend = Al::NCCLBackend; typename VectorType<Backend>::type = CUDAVector<float>; typename Backend::comm_type = Al::NCCLCommunicator; typename Backend::algo_type = Al::NCCLCollectiveAlgorithm]'
.../lbann/build/gnu.Release.surface.llnl.gov/aluminum/src/test/test_nccl_collectives.cpp:446:58:   required from 'void test_correctness() [with Backend = Al::NCCLBackend]'
.../lbann/build/gnu.Release.surface.llnl.gov/aluminum/src/test/test_nccl_collectives.cpp:470:39:   required from here
.../lbann/build/gnu.Release.surface.llnl.gov/aluminum/src/src/nccl_impl.hpp:335:57: error: 'ncclBroadcast' was not declared in this scope
                                 comm.m_nccl_comm, stream));
                                                         ^
.../lbann/build/gnu.Release.surface.llnl.gov/aluminum/src/src/nccl_impl.hpp:22:35: note: in definition of macro 'AL_CHECK_NCCL'
 #define AL_CHECK_NCCL(nccl_call) (nccl_call)

**Comment by JaeseungYeom** [comment]
I don't think I made any change to the build script or choosing different cuda toolkit. It was working until last time I built, which was probably a day ago or two.

**Comment by ndryden** [comment]
Should be fixed in 66ab3fb.

**Comment by JaeseungYeom** [comment]
Great. Thanks
