### ISSUE TITLE
Siamese triplet model without batchnorm hangs on pascal

### ISSUE THREAD

**Issue by JaeseungYeom** [LLNL/lbann#525]
It still runs on surface.
Batchnorm version runs on both pascal and surface.

**Comment by ndryden** [comment]
Can you provide the exact build details, runtime environment, and a command line to reproduce this?

**Comment by JaeseungYeom** [comment]
I built with --aluminum-with-nccl using the build script.
In the data reader, I used "first_n: 207032", and this job finishes one epoch in about 10 minutes on surface. However, on pascal, it timed out after three hours.
The command used was as below:
MV2_USE_CUDA=1 srun --nodes=1 --ntasks=2 --account=hpcdl --output=status-69937/stdout-%N.%t.txt --exclusive --cpu_bind=verbose --mpibind=off --cpu_bind=mask_cpu:0x000001ff,0x0003fe00 build/gnu.Release.pascal.llnl.gov/lbann/build/model_zoo/lbann --this_dir --model=model_triplet_alexnet.prototext --reader=data_reader_triplet.prototext --optimizer=opt_sgd.prototext

**Comment by timmoon10** [comment]
I see that model_zoo/models/siamese/triplet/data_reader_triplet.prototext tries to open data in lscratche. I've been told that it's being retired and that it was taken offline last night.

**Comment by timmoon10** [comment]
See #527.

**Comment by JaeseungYeom** [comment]
This is also caused by the same issue in #572, the env variable "OMP_PROC_BIND=true"
