### ISSUE TITLE
demise of lscratche breaks things

### ISSUE THREAD

**Issue by davidHysom** [LLNL/lbann#527]
The following files in the bamboo directory refer to lscratche:
- [ ] ./common_python/test_tools.py
- [ ] ./integration_tests/common_code.py
- [ ] ./integration_tests/full_alexnet.sh
- [ ] ./unit_tests/test_unit_check_proto_models.py

The following model_zoo/data_readers refer to lscratche:
- [ ] data_reader_ascii.prototext
- [ ] data_reader_imagenet.prototext
- [ ] data_reader_cub.prototext
- [ ] data_reader_triplet.prototext
- [ ] data_reader_triplet.prototext

The following expriment scripts refer to lscratche:
- [ ] run_lbann_cycgan_experiment.sh
- [ ] run_lbann_experiment.sh

The following build script refers to lscratche:
- [ ] scripts/build_lbann_lc.sh

**Comment by bvanessen** [comment]
We should move everything to look at lscratchh as it is the most future proof.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by davidHysom** [comment]
The following files are missing from lscratchh:
ls: cannot access /p/lscratchh/brainusr/datasets/tinyshakespeare/: No such file or directory
ls: cannot access /p/lscratchh/brainusr/datasets/tinyshakespeare/: No such file or directory
ls: cannot access /p/lscratchh/brainusr/datasets/CUB_200_2011/basic_set_256x256/: No such file or directory
ls: cannot access /p/lscratchh/brainusr/datasets/CUB_200_2011_list/train_list.txt: No such file or directory
ls: cannot access /p/lscratchh/brainusr/datasets/CUB_200_2011/basic_set_256x256/: No such file or directory
ls: cannot access /p/lscratchh/brainusr/datasets/CUB_200_2011_list/test_list.txt: No such file or directory

The following files have permission problems:
ls: cannot access /p/lscratchh/brainusr/datasets/ILSVRC2012/birds_and_cars/patches_84h_110x110_13x13-blur-ab_compact/train_list_8h_birds.txt: Permission denied
ls: cannot access /p/lscratchh/brainusr/datasets/ILSVRC2012/birds_and_cars/patches_84h_110x110_13x13-blur-ab_compact/val_list_8h.txt: Permission denied
ls: cannot access /p/lscratchh/brainusr/datasets/ILSVRC2012/patches_84h_110x110_13x13-blur-ab_compact/train/train_list_8h.nfl.npz: Permission denied

**Comment by forsyth2** [comment]
#528 merged, updating all of the files mentioned here to reference l-scratch-h instead of l-scratch-e. That pull request does not however take into account files missing from l-scratch-h or files with permission problems.
