### ISSUE TITLE
Create a self contained "smoke" test example

### ISSUE THREAD

**Issue by bvanessen** [LLNL/lbann#53]
We need a compiled binary that we can run to check that an installation of LBANN is correct.  The current idea is to create an autoencoder with synthetic data that can run for a fixed number of iterations and achieve a fixed reconstruction accuracy.  This test can then be setup for both model and data parallelism and can be used as a benchmark for installation on new systems and for validating the installation.

**Comment by timmoon10** [comment]
I think this is satisfied with the unit tests in model_zoo/tests/layer_tests.
