### ISSUE TITLE
tmux crashes LBANN

### ISSUE THREAD

**Issue by ndryden** [LLNL/lbann#556]
The signal handler in LBANN crashes upon receiving signal 28 (window size change). It appears that tmux on Ray sends this signal occasionally (even when the window size hasn't actually changed), which causes LBANN to abort.

**Comment by timmoon10** [comment]
Also, another reason why you should do everything in emacs!

**Comment by ndryden** [comment]
I don't know whether to be pleased at the emacs evangelism or called out about how I'm not using emacs for everything. 😉

**Comment by davidHysom** [comment]
This is out of my skillset and should be otherwise assigned. Also, what is emacs? 

Seriously, is this a bug? Should we be expect/support anyone using lbann to resize a window during execution?  Why?

**Comment by ndryden** [comment]
The problem is that we have a signal handler/stack trace/abort thing set up
for *every* signal now, even the benign/informational ones. And the ones
that are uncatchable. We need to whittle it down.

I’d propose only setting up a handler for floating-point exceptions,
segfaults, and maybe aborts.

**Comment by ndryden** [comment]
This is also annoying because when I ctrl-C an LBANN run, I get a giant set of stack traces that I don't really care about.

**Comment by ndryden** [comment]
A more complete list of signals we should handle: 4, 6, 7, 8, 11, 16, 31. Most of the rest of the signals are either meant to be handled by the default handlers in general (e.g. 2) or are informational and meant to be ignored if we don't care about them.
