### ISSUE TITLE
Build failure without Conduit

### ISSUE THREAD

**Issue by timmoon10** [LLNL/lbann#562]
### Description
When I build on Catalyst, I get the following error:
```text
In file included from /usr/workspace/wsa/moon13/src/lbann/src/data_store/jag_store.cpp:1:0:
/usr/workspace/wsa/moon13/src/lbann/include/lbann/data_store/jag_store.hpp:32:10: fatal error: conduit/cond\
uit.hpp: No such file or directory
 #include "conduit/conduit.hpp"
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/lbann.dir/src/data_store/jag_store.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```
We should either update the build script to include Conduit by default or avoid compiling `data_store/jag_store.hpp` when Conduit isn't detected.

### Build command
```bash
lbann/scripts/build_lbann_lc.sh --verbose --with-aluminum --clean-build
```

**Comment by davidHysom** [comment]
I put in guards to avoid compiling, and am testing a build now.
Conduit is undergoing active development, so I think it's too soon to include by default.

**Comment by davidHysom** [comment]
I pushed a bug fix; it built for me on catalyst without conduit.

**Comment by timmoon10** [comment]
Worked for me. Thanks!
