### ISSUE TITLE
Bug in CUDA-aware MVAPICH build

### ISSUE THREAD

**Issue by timmoon10** [LLNL/lbann#573]
A recent rebuild of CUDA-aware MVAPICH on Surface and Pascal has introduced a couple bugs. @ndryden has made a reproducer that hangs during GPU allgathers and he is in contact with LC.

For a temporary workaround, change: https://github.com/LLNL/lbann/blob/c0ec55afd562ead98e959dad10e20438e57d439f/scripts/build_lbann_lc.sh#L497 to:
```bash
MPI_HOME=/usr/global/tools/mpi/sideinstalls/${SYS_TYPE}/mvapich2-2.3/install-gcc-4.9.3-cuda-9.1
```

Possibly related issues: #572, #571.

**Comment by ndryden** [comment]
Tentatively, this is a bug in MVAPICH, and a ticket is being filed with the MVAPICH team. There is no ETA on any fix.
