### ISSUE TITLE
Unneeded optimizers created for biases

### ISSUE THREAD

**Issue by ndryden** [LLNL/lbann#584]
We still create a weight matrix and associated optimizer for biases even when a bias is not present in the convolution and fully-connected layers. We don't apply the bias during forward/backward prop, but it does lead to an unneeded optimization step and memory use.

**Comment by timmoon10** [comment]
Instead of adding more delicate logic to handle this case, it would be preferable to split out biases as their own separate layer (not dissimilar to how we split out the activations a year ago). If the Keras interface becomes widely adopted, this can be made invisible to the user.
