### ISSUE TITLE
Scatter is broken

### ISSUE THREAD

**Issue by samadejacobs** [LLNL/lbann#586]
comm->scatter() may be broken!  In particular, [ltfb assign_partners()](https://github.com/LLNL/lbann/blob/develop/src/callbacks/callback_ltfb.cpp#L43) calls scatter to get pairs of partners for LTFB tournament, at some point in training, every trainer/process is getting process/model 0 as its partner leading to stalling in order part of the code that calls MPI sendrcv/colectives. This bug is probably introduced recently as the code work just few days/weeks back. Also, I am observing this issue at number of processes >= 8.

**Comment by ndryden** [comment]
This is odd. No code related to `scatter` in LBANN has been touched in the past nine months, the code in Hydrogen hasn't been touched in four months, and I would be rather surprised if `MPI_Scatter` were broken. Are you sure this isn't a bug somewhere else in LTFB?

**Comment by samadejacobs** [comment]
Ok, I can debug further but what I know for now is that [assign_partners()](https://github.com/LLNL/lbann/blob/develop/src/callbacks/callback_ltfb.cpp#L43) returns 0 for all non-root processes at an iteration/step in the training and from that point the training stalled. The stalling should be expected because of send/rcv mismatches resulting from incorrect partners.

**Comment by timmoon10** [comment]
I don't reproduce this error after 13 LTFB rounds (LeNet; 24 MNIST epochs; 16 Pascal nodes, 2 procs/node; 16 models).

**Comment by samadejacobs** [comment]
Run command on Catalyst
`srun -n16 build/gnu.Debug.catalyst.llnl.gov/lbann/build/model_zoo/lbann --model=model_zoo/models/lenet_mnist/model_lenet_mnist.prototext --reader=model_zoo/data_readers/data_reader_mnist.prototext --optimizer=model_zoo/optimizers/opt_sgd.prototext `

Run command on Pascal
`srun --nodes=2 --ntasks=8  /usr/workspace/wsa/jacobs32/github.saj.lbann/build/gnu.Release.catalyst.llnl.gov/lbann/build/model_zoo/lbann --model=/usr/workspace/wsa/jacobs32/github.saj.lbann/model_zoo/models/lenet_mnist/model_lenet_mnist.prototext --num_epochs=10 --optimizer=/usr/workspace/wsa/jacobs32/github.saj.lbann/model_zoo/optimizers/opt_sgd.prototext --reader=/usr/workspace/wsa/jacobs32/github.saj.lbann/model_zoo/data_readers/data_reader_mnist.prototext `

It is default run/command for LeNet MNIST, except that you add ltfb callback. What is your round size? the problem should show up earlier (at around 5th LTFB rounds) if your round size is say 100 and show up later (at around 700 LTFB rounds) if your round size is say 10.

**Comment by timmoon10** [comment]
Closed with #597.
