### ISSUE TITLE
Potential increased memory usage in convolution layers

### ISSUE THREAD

**Issue by naoyam** [LLNL/lbann#587]
The current way the CUB memory pool is used can result in non-deterministic memory usage, where each convolution layer uses a separate workspace in the worst case. 

Consider a scenario like below:

```
1 acquire a buffer
2 call convolution
3 release the buffer
4 acquire a buffer
5 call convolution
6 release the buffer
```

At the second time a buffer is obtained from a pool, it is expected the same buffer is returned unless the required capacity exceeds the size of the first buffer. However, since releasing at line 3 does not actually release the buffer until the convolution at line 2 is completed, the buffer may not be reused and a new memory must be allocated at line 4. Thus, in the worst case, a new buffer may be allocated at each convolution layer. Since a workspace for convolution is always 1 GB, this can easily exhaust the GPU memory space.

The likelihood would be probably very small as it has not been observed yet, but I believe this can happen, and the fact that it's timing dependent can make it difficult to diagnose when it actually happens.

@timmoon10 Is there anything I'm misunderstanding?

**Comment by timmoon10** [comment]
There is a stream associated with each memory allocation and memory is available for its stream immediately after a deallocation is enqueued. I think our convolution workspace functionality is correct. We could, however, improve on it by choosing the workspace based on the available memory blocks in the allocator rather than hardcoding 1 GiB (#439).

**Comment by naoyam** [comment]
I don't think there is any correctness problem, but my concern is that the intended reuse of device buffers can be limited depending on runtime timings. If I understand the implementation of the CUB memory pool correctly, returning the memory to the pool does not mean the memory immediately becomes available for the stream. The memory is returned to a queue managed by the pool, but it is not going to be considered available until all preceding tasks on the stream at the time of releasing. In our case, the forward convolution may be still running on the stream when we request a new memory for the next convolution, so the pool won't give us the memory assigned to the first convolution but a different free memory.

**Comment by timmoon10** [comment]
If I read the code correctly, `DeviceAllocate` (https://github.com/NVlabs/cub/blob/1.8.0/cub/util_allocator.cuh#L400) looks through all free memory blocks that are either associated with the desired stream or which have completed. The block is immediately moved from the set `cached_blocks` to `live_blocks`. `DeviceFree` (https://github.com/NVlabs/cub/blob/c3cceac115c072fb63df1836ff46d8c60d9eb304/cub/util_allocator.cuh#L567) immediately moves a block from `live_blocks` back to `cached_blocks`.

**Comment by naoyam** [comment]
Ah, okay, you're right. I missed the conditional checking of the stream equivalence. Thanks for your explanation.
