### ISSUE TITLE
Scripts override model defaults

### ISSUE THREAD

**Issue by ndryden** [LLNL/lbann#6]
Our run scripts (e.g. `run_lbann_dnn_multi_mnist.sh`) set their own defaults for parameters (e.g. mini-batch size). These override the defaults set in the model zoo files. They probably shouldn't do that.

**Comment by davidHysom** [comment]
Since our prototext model_zoo driver is now working (though prototext files for all models have not yet been written and tested), I propose closing this issue, since it is no longer applicable to lbann's development path-forward. (um, can't believe I actually wrote path-forward ;)

**Comment by ndryden** [comment]
Concur, this problem has a nice solution now.

Closed!
