### ISSUE TITLE
Experiment script for Sierra/Lassen

### ISSUE THREAD

**Issue by timmoon10** [LLNL/lbann#601]
I think we should make an effort to put reasonable defaults in experiments/run_lbann_experiment.sh so that people can just run experiments without intimate knowledge of each system they run on. This is, of course, contingent on Sierra being stable enough to have good defaults at all.

**Comment by bvanessen** [comment]
Yes, please do that.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by naoyam** [comment]
Have we encountered any problem with (non-GDR) MVAPICH on Sierra?

**Comment by timmoon10** [comment]
@ndryden @naoyam Any progress with good stable defaults? @samadejacobs runs the following incantation:
```
jsrun -E AL_PROGRESS_RANKS_PER_NUMA_NODE=2 -E OMP_NUM_THREADS=4 -n 64 -r 1 -a 4 -b packed:11 -c 44 -g 4 build/gnu.Release.lassen.llnl.gov/lbann/build/model_zoo/lbann
```

**Comment by ndryden** [comment]
On Sierra, I use:
```
jsrun -E AL_PROGRESS_RANKS_PER_NUMA_NODE=2 -E OMP_NUM_THREADS=4 -d packed -b "packed:10" -n 4 -r 1 -a 4 -c 40 -g 4
```

When running into issues, there are various other environment variables you can set to disable certain things in SMPI (e.g. `-E HCOLL_ML_DISABLE_BCAST=1` for hangs in `MPI_Bcast`).

**Comment by naoyam** [comment]
Why do you limit the number of OpenMP threads to 4?

**Comment by ndryden** [comment]
I'm not sure if that's optimal, I haven't been running much on Sierra where I/O or CPU compute matters. Originally I based it on assigning one thread per L2 cache, with the Aluminum progress engine taking the fifth one, and excluding the eleventh one.

**Comment by timmoon10** [comment]
Can we have these incorporated into experiments/run_lbann_experiment.sh?
