### ISSUE TITLE
Switch to template-based programming style for data layout

### ISSUE THREAD

**Issue by bvanessen** [LLNL/lbann#61]
Currently we are specializing the data distribution for each layer and other related classes via a parameter passed into the constructor.  This then requires us to provide dynamic code that sets up and then type casts core object data structures into concrete Elemental distributed matrices.  It would be a heavy lift to switch over to a more templated code base, but may make the implementation cleaner.  I would like to have a discussion and thoughts about this.  If we chose to move forward it would have to be a deliver freeze and refactor to help minimize churn.

**Comment by ndryden** [comment]
I think this would be a good move. It should clean up the code and avoid runtime checks for what distribution data is in.

If we do this, it would probably be best to do it as part of a larger chunk of cleanup work to avoid multiple freezes and refactorings.

**Comment by bvanessen** [comment]
All of the appropriate layer classes are now templated.  I still need to go in and update them to make effective use of the templates.  That will happen after the layer class is split up.
