### ISSUE TITLE
Framework for layer unit tests

### ISSUE THREAD

**Issue by timmoon10** [LLNL/lbann#624]
### Problem
As we move into more interesting models, the number of supported layers has been growing steadily. I've also added 27 new layers in #623. We need a more systematic way to test all of our layer implementations.

### Proposed pathway
- [x] Implement a weights initializer that allows the user to directly specify weight values.
- [x] Implement a "weights layer" that simply outputs the values of a set of weights.
- [x] Implement a callback that throws an error if the objective function value is not within a specified range.
- [x] Implement an L2 norm layer. This is helpful for gradient checking since its error signal varies with its input values.
- [ ] Implement simple unit tests for as many layers as possible. For most layers, it should be sufficient to have weights layers of size O(5), the tested layer, and an L2 norm layer. The objective function callback should check whether the objective function value matches an externally computed value. If the layer is differentiable, gradient checking should be performed.
- [x] Once this framework is established, a unit test will be required for acceptance of new layers. In most cases this will just be a matter of copy-pasting another unit test, swapping out the tested layer, and updating the expected objective function value.

### Questions
- Each test should be small and fast, but will we run into any issues if we suddenly plonk down ~50 of them? Will we want to tinker with our Bamboo interface? Pinging @forsyth2.

**Comment by ndryden** [comment]
I just wanted to say that I endorse having more unit tests.

**Comment by forsyth2** [comment]
I don't think adding more fast unit tests will place much strain on Bamboo. Just make sure you add them in `bamboo/unit_tests` so Bamboo can see them. Tests currently in that directory should serve as good examples.
