### ISSUE TITLE
Refactor data readers main loop for fetch_data / fetch_label

### ISSUE THREAD

**Issue by bvanessen** [LLNL/lbann#63]
so that it is not data reader specific.  Create a fetch_datum function for each data reader that is called by the higher level fetch_data function.  This will allow us to mess with loop bounds and OpenMP parallelism once.

**Comment by davidHysom** [comment]
I'm scratching my head over this. I (think) I get the concept of having OpenMP calls at a higher level, but I don't have any good ideas about how fetch_datum would work. If multiple threads are calling fetch_datum, the fetch_datum is going to have to sort-of serialize the calls. Perhaps I'm missing something ...

**Comment by bvanessen** [comment]
This feature has been added as of commit c74c6ca07d528ebdb83eca8be0190e08f876a7c1
