### ISSUE TITLE
What do we mean by "multiple models"?

### ISSUE THREAD

**Issue by timmoon10** [LLNL/lbann#639]
Copy-pasting some thoughts from https://github.com/LLNL/lbann/pull/637:

> Things are starting to get confusing since we are overloading the term "multiple models". It can either refer to multiple model types (e.g. generators and discriminators in GANs) or multiple model instances (e.g. for quantization and our current implementation of LTFB). One solution is to reserve the term "multiple models" for distinct model architectures and to use the term "multiple model instances" for instantiations of the same model architecture (possibly with different weight values, hyperparameters, etc.). Alternatively, we can scrap the whole ""model instances" idea and just support the ability to associate a given model class with a subcommunicator. Our current scheme with identically sized "model communicators" is awkward and restrictive, so I think this is a better long-term solution.

**Comment by ndryden** [comment]
The interfaces we're using for "multiple models" were originally meant to support data-parallel training, and I think they're straining under the various ways we've hacked things onto them (LTFB, GANs, etc.). It's in that context that the even partitioning of the world communicator is done.

I think we should split this into (at least) two different sets of functionality, neither of which we have in entirety right now.
1. Model replicas for data-parallel training. We should be able to mark (potentially distributed) weight matrices as replicas of each other, and LBANN can keep them in sync automatically (performing the necessary allreduces, potentially with quantization). This is slightly different from what we currently have, where a model performs within-model allreduces for data-parallel layers, and then a separate pass to synchronize the model replicas. Purely data-parallel layers should do only a single allreduce; model-parallel layers should do their computation within their model replica, then be synchronized with an allreduce.
2. Separate models and arbitrary partitions of the world grid. This would be to support things like GANs or LTFB.

**Comment by bvanessen** [comment]
I think that the idea of a trainer is a good abstraction from model and is the language that I use to describe LTFB. 

Roughly, I would think of a trainer as a set of nodes that is working on a model instance.  If could also indicate distinct compute resources.  Then if each trainer is working with the same model, that could be a data parallel case, or LTFB if they run tournaments.

Anyway, I will have to complete this thought more later.   Have to get back to PAs.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by timmoon10** [comment]
This ambiguity has been cleared up by changing terminology from "multiple models" to "multiple trainers."
