### ISSUE TITLE
Unclear result reporting

### ISSUE THREAD

**Issue by timmoon10** [LLNL/lbann#640]
Each time we report a result, e.g. objective functions, metrics, or timings, we need to specify the result name, execution mode, epoch, model instance. Our current output looks something like:
```
Model 2 training epoch 3 mean squared error : 12.345
```

This is still readable, but on the edge of being ungrammatical. #637 might also report the model name, so I think we need to think about a better approach than just stringing together all the identifiers in an arbitrary order. Perhaps something like:
```
[model "gen", model instance 3, training, epoch 3] mean squared error : 12.345
```

I'll admit it's ugly, but it's much more readable than what we've got.

Another concern is verbosity and redundant information. For instance, if there is only one model instance, it might be convenient to avoid reporting "model instance 0" every single time. However, allowing the reporting format to change will make it harder to write and maintain parsing scripts, e.g. those for our Bamboo regression tests.

Finally, we also need to settle the terminology issues in #639 to ensure our identifiers are unambiguous.

**Comment by bvanessen** [comment]
Additionally, while we want to maintain readability, we want to make sure that a script can easily parse it.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by ndryden** [comment]
I disagree-- those are pretty opposed goals. If we want something for scripts to parse, we should leverage the summarizer, and if that's insufficient, we should extend it or add other logging APIs. If we want something for users to interpret, we should focus on making it pretty and interpretable (I'm sure there are plenty of libraries we could leverage for this). Trying to do both at the same time is likely to do both poorly.

**Comment by bvanessen** [comment]
I understand you concern and recommendation.  I am not saying that in the general case we want to extract lots of data from the log files, but I believe that the bamboo infrastructure greps out lines and I know that I have done that as well when debugging a run.  So I don’t want to make the inordinately hard.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470
