### ISSUE TITLE
Building without CUDA gives build error

### ISSUE THREAD

**Issue by benson31** [LLNL/lbann#649]
I think there's an issue with the layer.hpp file (and corresponding .cpp) when no CUDA support. The offending commits are: https://github.com/LLNL/lbann/commit/cc121244cbc7c163eb444066c6403fd770f19a75 and https://github.com/LLNL/lbann/commit/a2733f5adbe82bf0bb94d08cec770c9dae194f5c. @bvanessen

**Comment by bvanessen** [comment]
Okay, I will fix it.  Sorry.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by benson31** [comment]
@davidHysom This is the reason for your current build issue. You can work around this by enabling cuda in the build.

**Comment by bvanessen** [comment]
Closed with PR #651
