### ISSUE TITLE
Incorrect timings with LTFB

### ISSUE THREAD

**Issue by timmoon10** [LLNL/lbann#670]
Our timer callback gives wonky results with LTFB, like `(epoch run time) < (average mini-batch time) x (number of mini-batches)`. Looking closer, this is because LTFB changes the execution mode in the middle of a training epoch. The timer callback resets its data at the beginning of a training/validation/testing epoch, so starting LTFB evaluation will wipe out any preceding timing data for the training epoch. The easiest fix is to keep separate timing data for each execution mode.

**Comment by ndryden** [comment]
How much of this is due to our abuse of the data-parallel multi-model code for LTFB?

**Comment by bvanessen** [comment]
Sounds like a reasonable plan to have separate timers for each execution mode.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by samadejacobs** [comment]
How is LTFB abuse of data-parallel? LTFB is an instance of data-parallel.

**Comment by ndryden** [comment]
The typical data-parallel formulation in deep learning involves a single model being replicated. LTFB trains with different models.
