### ISSUE TITLE
CIFAR-10 support for partitioned I/O layers

### ISSUE THREAD

**Issue by bvanessen** [LLNL/lbann#68]
Add support to the CIFAR-10 data reader.

**Comment by davidHysom** [comment]
could you expand as to what's needed here?

**Comment by bvanessen** [comment]
Yes.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by bvanessen** [comment]
Support for this was added in the data reader refactoring.  c74c6ca07d528ebdb83eca8be0190e08f876a7c1
