### ISSUE TITLE
Fix recording of indices in data reader

### ISSUE THREAD

**Issue by bvanessen** [LLNL/lbann#689]
When part of the data store when it, it squashed the recording of indices that are reported by the callback.  This should be fixed and harmonized since the two features are similar.

**Comment by davidHysom** [comment]
>When part of the data store when it, it ...
I think you're channeling Trump -? Please clarify.

**Comment by bvanessen** [comment]
Fixed in commit 9da41ffc961cdf28d96ff9e9893875bee357a8c0.
