### ISSUE TITLE
API layer for generic layer and model

### ISSUE THREAD

**Issue by bvanessen** [LLNL/lbann#69]
Re-evaluate if we have the interface that we need, and help provide some encapsulation.  Work to provide consistency for the various sections of public / private / protected kicking around - fix
encapsulation

**Comment by bvanessen** [comment]
Let remember that this is both 5 and 5a.

**Comment by ndryden** [comment]
After some recent changes making `m_activations` &co protected in the `Layer` class, plus the `setup` changes, I think this can now be called done. Anything more specific we can probably discuss as separate, focused issues.
