### ISSUE TITLE
Error during finalization

### ISSUE THREAD

**Issue by timmoon10** [LLNL/lbann#717]
When I run on two Pascal nodes with a default build (GCC 4.9.3, MVAPICH2 2.3rc2, CUDA 9.1), I get some errors at the end of the program:
```
Warning: MPI was finalized before Elemental.
Warning: MPI was finalized before Elemental.
Attempting to use an MPI routine after finalizing MPICH
Attempting to use an MPI routine after finalizing MPICH
srun: error: pascal10: tasks 0-1: Exited with exit code 1
```

It looks like a destructor is doing something wonky, perhaps in Hydrogen. The non-zero exit code messes with the Bamboo unit tests, so we should fix this before Bamboo comes back online (#661).

**Comment by ndryden** [comment]
One possibility is that Aluminum could be finalizing MPI. However, Aluminum only does this if it initialized MPI in the first place.

**Comment by benson31** [comment]
I hadn't thought about the bamboo issue. I'll dig into it.

**Comment by timmoon10** [comment]
I don't see this anymore.
