### ISSUE TITLE
Constructing layers - too many options

### ISSUE THREAD

**Issue by bvanessen** [LLNL/lbann#75]
passing string and foo versus passing objects
- can we get rid of this duplication - pick one (probably objects)

**Comment by davidHysom** [comment]
For the new model_zoo/lbann_proto driver, all layers are constructed by directly calling the layer's constructor. The code for constructing layers by passing the lbann_model a string is goofy, since it only supports fully_connected and softmax.

**Comment by samadejacobs** [comment]
I will go with calling the layer's constructor option since it is now comparably more general. I will clean up the code appropriately.

**Comment by samadejacobs** [comment]
On a further review, I think that we should keep the layer add method that takes string and other parameters. That method has layer factory, this I believe is redundant and we may not need. The code benefit from simplicity and compactness if we take this approach. For instance, the add method that takes string internally compute layer index, previous layer dimension etc. We can easily extend the method to support convnet (alexnet) layers and this will address David's question/concern.

**Comment by ndryden** [comment]
Whenever anyone adds a new layer type we'd need to update this method to support it as well. I think, while it might be a bit more verbose, sticking with the constructor is superior and avoids confusion.

**Comment by davidHysom** [comment]
I agree with Tim. Note, when we go completely to building models using prototext, each layer looks something like this:

layer {
  fully_connected {
    ...
  }
  index: 3
  parent: 2
  child: 5
}

Code in src/proto/lbann_proto will handle keeping track of
layer indices, num neurons in each, etc.

**Comment by bvanessen** [comment]
It sounds like getting rid of the string and layer factory is still the way to go, especially since we are moving to prototxt.

**Comment by samadejacobs** [comment]
I believe protoxt replacing model zoo is a stronger argument but is it ready as at now? if yes, then I can just get rid of the string and layer factory and not need to update model zoos that are using string add method (actually that will be all the model zoos). If not, then I have to replace pass string with passing objects in all model zoos.

**Comment by davidHysom** [comment]
yes, it's working. I have prototext files for dnn_mnist, cnn_mnist, and one of the autoencoders

________________________________

**Comment by samadejacobs** [comment]
Ok, am about to commit this as discussed, all model zoo will be broken, users have to use protoxt approach

**Comment by bvanessen** [comment]
Or switch over to adding them via constructor.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by samadejacobs** [comment]
Yes, I could do that except I don't know how useful it will be to go through all model zoo since we are switching to prototxt. I could do it for one or two model zoos just for reference.

**Comment by davidHysom** [comment]
suggest you edit the CMakeLists.txt to remove/comment out the drivers, so the build won't break

________________________________

**Comment by samadejacobs** [comment]
DNN MNIST model zoo is fixed and enabled. We can consider this task done for now.

**Comment by ndryden** [comment]
Are the auto-encoders working again too after the temporary changes I made to fix the build?

**Comment by samadejacobs** [comment]
My understanding (from David's response) is that auto-encoder is working with prototext. We could have the model zoo version just for legacy purposes.

**Comment by ndryden** [comment]
@samadejacobs I meant the stacked autoencoder model (see [here](https://github.com/LLNL/lbann/blob/release-v0.93/src/models/lbann_model_stacked_autoencoder.cpp#L68)), which I presume is currently broken and needs to be updated. If not, we should delete the relevant code.

**Comment by davidHysom** [comment]
How do you know it's broken? I checked, and there are no drivers in the model_zoo that uses it.

However, lbann_prototext_common.cpp will instantiate one:


  } else if (name == "stacked_autoencoder") {
    model = new stacked_autoencoder(mini_batch_size, comm, obj, lfac, optimizer_fac);

So a path forward might be to copy greedy_layerwise_autoencoder_mnist.prototext

to stacked_autoencoder.prototext, and modify as needed. Unf. I don't know enough

about autoencoders to do that.

________________________________

**Comment by ndryden** [comment]
Fixed with @samadejacobs's commit.
