### ISSUE TITLE
Document our layers better

### ISSUE THREAD

**Issue by ndryden** [LLNL/lbann#758]
We should have better documentation describing our layers. Many of our layers have documentation of the form `/** X layer */`, where `X` is the name of the layer. That is basically worse than useless (I could be saving several bytes of disk space!).

**Comment by timmoon10** [comment]
To be fair, a lot of our documentation is a formality to make Doxygen look nice. You are right this is an area we need to improve. Can you make this more concrete and provide action items?

**Comment by bvanessen** [comment]
I will put together a list of action items for this.  

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by ndryden** [comment]
I'll let Brian come up with a list of particular things, but to get things started, here are a few things I think are relevant.
* The Google C++ style guide has a [nice section on comments and documentation](https://google.github.io/styleguide/cppguide.html#Comments). They also have an entirely [separate guide dedicated just to documentation style](https://developers.google.com/style/). The [section on API reference code comments](https://developers.google.com/style/api-reference-comments) in particular is relevant. (The "Do not repeat the class name in the first sentence" part in particular is calling us out.)
* The API reference documentation for e.g. TensorFlow or PyTorch is all generated from comments in code. We should aim to be at least as descriptive as they are. For example, `tf.nn.weighted_cross_entropy_with_logits` ([API](https://www.tensorflow.org/api_docs/python/tf/nn/weighted_cross_entropy_with_logits) and [source](https://github.com/tensorflow/tensorflow/blob/r1.12/tensorflow/python/ops/nn_impl.py#L187)) is a good one. Or PyTorch's convolution documentation ([API](https://pytorch.org/docs/stable/nn.html#convolution-layers) and [source](https://pytorch.org/docs/stable/_modules/torch/nn/modules/conv.html#Conv1d)).
