### ISSUE TITLE
All links in the CMake section of the README are dead

### ISSUE THREAD

**Issue by goxberry** [LLNL/lbann#762]
(The title should be self-explanatory, but if it's not, I'm happy to clarify.)

**Comment by bvanessen** [comment]
Yes, I need to update them.  I would be happy to chat with you about the project if you want.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by timmoon10** [comment]
As far as I can tell, we've cleaned up all of our dead links.
