### ISSUE TITLE
Runtime parameters

### ISSUE THREAD

**Issue by bvanessen** [LLNL/lbann#79]
Switch the parameters interface from the Elemental choice package to Hysom’s option package, which gives us the option to specify via files as well as command line.

**Comment by davidHysom** [comment]
This is useful for the prototext approach. The scenario is that this class can be used to over-ride some values (e.g, mini batch size; num epochs) that are specified in prototext files. So an important question is: for which parameters do we want to provide the ability to over-ride? The current lbann_proto driver (using a different mechanism) allows you to over-ride num-epochs and mini-batch-size. What else would be useful?

This isn't something that needs a quick answer. Rather, I view it as ongoing: when a user says, "it would be useful if I could over-ride this param on the command line, as opposed to editing the prototext file" -- at that point we can make the enhancement.

**Comment by bvanessen** [comment]
We have moved this out of the v0.93 release process.

**Comment by davidHysom** [comment]
This is fully implemented, so am closing.
