### ISSUE TITLE
Scale augmentation

### ISSUE THREAD

**Issue by ndryden** [LLNL/lbann#804]
ResNet (and many other modern training pipelines) use scale augmentation: an image is resized such that its shorter side is selected from the range `[a, b]` uniformly at random. I don't believe our preprocessing pipeline supports this. It is cropped after this (typically also at random, we already support this).

**Comment by ndryden** [comment]
Similarly, we should also support combined scale/aspect ratio augmentation, which is commonly used for Inception training (and some ResNet training pipelines use it instead). It's basically the PyTorch [RandomResizedCrop](https://pytorch.org/docs/stable/torchvision/transforms.html#torchvision.transforms.RandomResizedCrop) transform. (You can go through the source to see exactly how it's implemented.)

**Comment by timmoon10** [comment]
`RandomResizedCrop` was added as a preprocessor transform in PR #1014.
