### ISSUE TITLE
model parallelism demonstration

### ISSUE THREAD

**Issue by antoajayraj** [LLNL/lbann#826]
Is there any good code sample to demonstrate model parallelism on lbann ?

**Comment by bvanessen** [comment]
Given any neural network model the individual layers are setup for either data or model parallelism based on a per-layer keyword in the model’s prototext.  The alexnet model uses model parallelism for the fully connected layers as do the pilot1 models.  Our new work on spatial decomposition for distributed convolutions is on a separate repo branch.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by antoajayraj** [comment]
Can you please point me to the 'spatial decomposition for distributed convolutions' repo ?

**Comment by bvanessen** [comment]
I will put you in touch with the members of my team working on this.  I am curious about who you are and what institution you are working for?  What sort of problem are you planning on using LBANN for?

Thanks,

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by antoajayraj** [comment]
@bvanessen sent u my details in email
