### ISSUE TITLE
Layer selection function based on layer class category

### ISSUE THREAD

**Issue by bvanessen** [LLNL/lbann#84]
We need an accessor function that will get all of the layers in a model of a certain type, e.g. learning, transform, etc.  This is especially necessary in the callbacks so that we can pick a common parent that has the appropriate data structures.

**Comment by ndryden** [comment]
I have added partial support for this in models with an overloaded `get_layers` method that takes a `layer_category` argument. It's only partial because we need to re-jigger the `layer_category` categories.

**Comment by ndryden** [comment]
On that topic, I propose the following finer-grained categories: `io`, `learning`, `activation`, `regularizer`, `transform`, `special`, `invalid`.
