### ISSUE TITLE
Building lbann fails with undefined reference to "lbann::lbann_quantizer::NUM_BITS"

### ISSUE THREAD

**Issue by antoajayraj** [LLNL/lbann#843]
We are trying to build LBANN and hit upon the following problem on a power system machine. (ppc64le)

cmake went fine, but when we try to do a make, we hit the following issue;

[ 80%] Building CUDA object CMakeFiles/lbann.dir/src/layers/misc/covariance.cu.o
[ 80%] Building CUDA object CMakeFiles/lbann.dir/src/layers/misc/variance.cu.o
[ 81%] Building CUDA object CMakeFiles/lbann.dir/src/layers/misc/channelwise_mean.cu.o
[ 81%] Building CUDA object CMakeFiles/lbann.dir/src/layers/regularizers/batch_normalization.cu.o
[ 81%] Building CUDA object CMakeFiles/lbann.dir/src/layers/transform/crop.cu.o
[ 82%] Building CUDA object CMakeFiles/lbann.dir/src/layers/transform/in_top_k.cu.o
[ 82%] Building CUDA object CMakeFiles/lbann.dir/src/layers/transform/sort.cu.o
[ 82%] Building CUDA object CMakeFiles/lbann.dir/src/layers/transform/tessellate.cu.o
[ 83%] Building CUDA object CMakeFiles/lbann.dir/src/objective_functions/weight_regularization/l2.cu.o
[ 83%] Building CUDA object CMakeFiles/lbann.dir/src/optimizers/adagrad.cu.o
[ 84%] Building CUDA object CMakeFiles/lbann.dir/src/optimizers/adam.cu.o
[ 84%] Building CUDA object CMakeFiles/lbann.dir/src/optimizers/sgd.cu.o
[ 84%] Building CUDA object CMakeFiles/lbann.dir/src/utils/cuda.cu.o
/home/guest/anto/LBANN/lbann/src/utils/cuda.cu(69): warning: expression has no effect

/home/guest/anto/LBANN/lbann/src/utils/cuda.cu(69): warning: expression has no effect

[ 85%] Linking CUDA device code CMakeFiles/lbann.dir/cmake_device_link.o
[ 85%] Linking CXX shared library liblbann.so
[ 85%] Built target lbann
Scanning dependencies of target jag_converter-bin
[ 85%] Building CXX object src/data_store/CMakeFiles/jag_converter-bin.dir/jag_converter.cpp.o
[ 85%] Linking CUDA device code CMakeFiles/jag_converter-bin.dir/cmake_device_link.o
[ 86%] Linking CXX executable jag_converter
../../liblbann.so: undefined reference to `lbann::lbann_quantizer::NUM_BITS'
collect2: error: ld returned 1 exit status
src/data_store/CMakeFiles/jag_converter-bin.dir/build.make:168: recipe for target 'src/data_store/jag_converter' failed
make[2]: *** [src/data_store/jag_converter] Error 1
CMakeFiles/Makefile2:914: recipe for target 'src/data_store/CMakeFiles/jag_converter-bin.dir/all' failed
make[1]: *** [src/data_store/CMakeFiles/jag_converter-bin.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Any help is very much appreciated.

**Comment by ndryden** [comment]
I just built without issue on a POWER9 system. The `lbann_quantizer` and related code were removed recently, so I suspect that some components of your build are outdated. Can you try a clean build?
