### ISSUE TITLE
Revamped Fully connected layer has to have option for no bias term

### ISSUE THREAD

**Issue by bvanessen** [LLNL/lbann#85]
Since it is now more general purpose, we have to be able to remove the bias term.

**Comment by bvanessen** [comment]
I talked with Tim about this last night, but since we are going to have the fully connected layer be general purpose, we either need to have a constructor argument that disables the bias term (boolean, or if you put in bias term = 0.0 then no memory is allocated) or has a templated design that creates two versions of the layer.  I may get to this today, but if not we need to get this working before we can get things like softmax to work the same.

**Comment by bvanessen** [comment]
I have added a boolean flag that should do the trick for now.  When we add the fully connected layers to the models and place the value false in the last constructor argument to disable the bias term.  This is mostly necessary for the layer just proceeding the softmax activation.

**Comment by ndryden** [comment]
@timmoon10 We fixed some issues with the bias term and need to clean that up.
