### ISSUE TITLE
running lbann on multiple gpu's

### ISSUE THREAD

**Issue by Raviteja1996** [LLNL/lbann#858]
Hello while running LBANN its running fine, but when I checked how many GPU's it is using its using only one. I have 4 available total, so can I know how to use them all while running LBANN

**Comment by bvanessen** [comment]
LBANN is designed to use one rank per GPU and it will report its configuration as it starts up.  Launch the mpi job with 4 ranks and you should be good.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by Raviteja1996** [comment]
Hey I am new to this can you tell me how to do it. It would be a helpful. Thank you.
