### ISSUE TITLE
Running model using model parallelism

### ISSUE THREAD

**Issue by Raviteja1996** [LLNL/lbann#860]
Hello when I am running the model successfully using "data_parallelism". But I want to run it using model parallelism, so I tried changing the .prototext file, replacing data_parallelism to model_parallelism but there came an error showing "/lbann/include/lbann/layers/io/input/input_layer.hpp 81 :: input_layer with partitioned_io_buffer does not supports MODEL_PARALLEL data layout". When I checked that file, in the code when ever an model parallelism is called there was an error raised and the same error is being showed. So can you help me how to come over this problem.

**Comment by bvanessen** [comment]
The input layers no longer support model parallelism, but then again you don’t really want to split up the data that way.  Model parallelism is excellent for the fully connected layers if they are large.  Most traditional convolutions are best suited with data parallelism and you can mix and match within a single model.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470
