### ISSUE TITLE
Toward Python-based experiment workflow

### ISSUE THREAD

**Issue by oyamay** [LLNL/lbann#861]
If we move to a Python-based workflow, users may confuse that they have to run two scripts to perform one experiment, `network.py` and `run_lbann_experiment.sh`.

So how about make `run_lbann_experiment.sh` to accept a `--python` argument? A debugging user
1. tunes network and/or hyper-parameters in `network.py`
2. runs `run_lbann_experiment.sh`

and `run_lbann_experiment.sh --python network.py` internally runs `network.py`.
This workflow can also hide a bothering intermediate file (namely `network.prototext`).

An experimental branch for this is in [oyamay/python-experiment-workflow](/oyamay/lbann/tree/python-experiment-workflow).
A Python script needs to have the following code to parse the argument:

```python
import argparse
import lbann.config_generator as lcg

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--model-arg", action="store", type=int)
    args,_ = parser.parse_known_args()
    lcg.save_prototext(
        create_model(args.model_arg),
        create_data_reader(),
        create_optimizer())
```

**Comment by davidHysom** [comment]
anything you do in a shell script can be done in python. I would much prefer to convert experiment scripts to python. I believe this increases the chances for finer-grained interoperability.
________________________________

**Comment by oyamay** [comment]
I agree. But since the current LBANN is based on MPI and batch-queue systems, we still have to run several commands to create a shell script and issue a job, which is already implemented in the shell script and several variations of it.
So if we don't want to reinvent the wheel, this is a quick solution for it.

**Comment by oyamay** [comment]
This relates to #941.
