### ISSUE TITLE
Regarding usage of CPU rather than GPU

### ISSUE THREAD

**Issue by Raviteja1996** [LLNL/lbann#867]
Can we run LBANN only on CPU without involving GPU even if the GPU is present?

**Comment by bvanessen** [comment]
Pass the —disable_cuda command line argument check —help for the exact syntax


Brian C. Van Essen

vanessen1@llnl.gov<mailto:vanessen1@llnl.gov>

(w) 925-422-9300

(c) 925-290-5470

---

Sent from my iPhone

On Feb 8, 2019, at 1:45 AM, Raviteja1996 <notifications@github.com<mailto:notifications@github.com>> wrote:


Can we run LBANN only on CPU without involving GPU even if the GPU is present?
