### ISSUE TITLE
Rethink how layers allocate data via the setup function

### ISSUE THREAD

**Issue by bvanessen** [LLNL/lbann#87]
Right now the setup function in fully connected will allocate / zero out all of the matrices that it uses, rather than relying on the parent classes to allocate space for their respective fields.  We should check to see if this is still what we want to do with our new structure.

**Comment by ndryden** [comment]
I would propose that `Layer` initialize the matrices it declares (`activations` and `error_signal`). This should simplify `setup` not just in `fully_connected`, but in many other layers (`convolution`, `activation`, etc...). It can also set up the relevant views.

Additionally, we `Zeros` `prev_activations` and `prev_error_signal`, which seems unnecessary: these are either views, or if the data distribution differs, `El::Copy` is called, which handles the resizing anyway. Am I missing something?

(If a layer needs to do something differently, it can always reallocate during setup.)

**Comment by bvanessen** [comment]
Overall, I think that this is a good approach, especially to not have a layer initialize its previous activations or error.

Brian

On Jun 22, 2017, at 10:41 AM, Nikoli Dryden <notifications@github.com<mailto:notifications@github.com>> wrote:


I would propose that Layer initialize the matrices it declares (activations and error_signal). This should simplify setup not just in fully_connected, but in many other layers (convolution, activation, etc...). It can also set up the relevant views.

Additionally, we Zeros prev_activations and prev_error_signal, which seems unnecessary: these are either views, or if the data distribution differs, El::Copy is called, which handles the resizing anyway. Am I missing something?

(If a layer needs to do something differently, it can always reallocate during setup.)

**Comment by ndryden** [comment]
Done in 16346b20a6531d256c25decf2a44fed152cdde17.

Tested a few different configurations and things seem to work.
