### ISSUE TITLE
error: 'get_basename_without_ext' `get_ext_name' was not declared in this scope

### ISSUE THREAD

**Issue by mxmlnkn** [LLNL/lbann#871]
When trying to compile release 0.98, I get a compile error:

    [ 66%] Building CXX object CMakeFiles/lbann.dir/src/utils/threads/thread_pool.cpp.o
    /opt/lbann-0.98/src/proto/proto_common.cpp: In function 'void lbann::customize_data_readers_index_list(lbann::lbann_comm*, lbann_data::LbannPB&)':
    /opt/lbann-0.98/src/proto/proto_common.cpp:638:28: error: 'get_basename_without_ext' was not declared in this scope
         std::string basename = get_basename_without_ext(r->index_list());
                                ^~~~~~~~~~~~~~~~~~~~~~~~
    /opt/lbann-0.98/src/proto/proto_common.cpp:639:23: error: 'get_ext_name' was not declared in this scope
         std::string ext = get_ext_name(r->index_list());
                           ^~~~~~~~~~~~
    /opt/lbann-0.98/src/proto/proto_common.cpp:639:23: note: suggested alternative: 'gethostname'
         std::string ext = get_ext_name(r->index_list());
                           ^~~~~~~~~~~~
                           gethostname

It seems to be fixed by adding `#include "lbann/utils/file_utils.hpp"` to `src/proto/proto_common.cpp`

**Comment by ndryden** [comment]
I have fixed this in the develop branch. Thanks for reporting this!

**Comment by bvanessen** [comment]
Thanks for finding this.  I have fixed it in v0.98.1

**Comment by mxmlnkn** [comment]
@bvanessen Thank you. It compiles now.
