### ISSUE TITLE
Normalize constructor arguments

### ISSUE THREAD

**Issue by ndryden** [LLNL/lbann#88]
The arguments to constructors within the layer hierarchy are all over the place. We should pick a single ordering and avoid unneeded parameters (if possible).

**Comment by ndryden** [comment]
@timmoon10 The convolution, LRN, and pooling layer constructors take a hodgepodge of `int`/`El::Int` arguments.

**Comment by bvanessen** [comment]
I am working on the making the template have more convfefe, which will remove the first argument for many of them.

**Comment by bvanessen** [comment]
I think that this is mostly done, but could use a pass in the post refactor cleanup.

**Comment by davidHysom** [comment]
I believe the ordering of parameters to layers (at least to terminal layers) is mostly consistent, except for files in layers/activations.

**Comment by timmoon10** [comment]
Layer constructor arguments are much cleaner as of b060aff05dceddf88d043c3e1708b24d47a14dac. `int`s are used as the standard integer type and unnecessary arguments are deleted. However, as discussed in #91, we may wish to change some integer arguments to `El::Int`. Also, I haven't put any work into standardizing argument ordering.

**Comment by ndryden** [comment]
I think we've met the intended goal of this issue. Any further argument normalization/code cleanup should have separate, more precise issues created.
