### ISSUE TITLE
Non-deterministic performance when varying number of ranks in model

### ISSUE THREAD

**Issue by bvanessen** [LLNL/lbann#9]
There is a set of issues that we discovered that lead to non-determinism when you vary the ranks within the model.  The easy problem is that if you do not explicitly initialize the random seed for LBANN there is a variation in train and test accuracy as you change the number of MPI ranks.  The simple solution is to use init_random(const e.g. 42); in the model_zoo file.  A more important issue is that the initialization of the matrices when doing He or Xavier initialization uses a Elemental function that generates parallel random numbers.  Given that initialization is done rarely, we need to add a default mode that will generate the random sequence from a single root node.  As a performance optimization we can keep the parallel initialization as a compile time option.  A secondary issue has to do with dropout.  In the current implementation each rank generates a parallel set of random numbers to determine which nodes to drop out.  We want to keep this behavior for performance reasons, but add in a "serial" mode that uses a global, consistent, random sequence.

**Comment by ndryden** [comment]
The first part is now partially addressed through the `fill_gaussian` &co. methods added in 1b1261.

However, I still get varying performance as the number of processors varies, even when doing a sanity check of initializing the `WB` matrices with `Zeros`. Where else do we use random numbers that might affect this?

**Comment by ndryden** [comment]
Checked into this again on the latest LBANN: Using the `distributed_minibatch` input/target layers there's no varying performance as the number of processors varies. I assume the problems I was getting before were due to bugs in the input layer.

Will have the dropout stuff done soon.
