### ISSUE TITLE
Follow the rule of three/five

### ISSUE THREAD

**Issue by ndryden** [LLNL/lbann#90]
We have plenty of classes (I think, nearly all) that define destructors, but none (or nearly none) define copy constructors or copy assignment operators. This hasn't been an issue because we haven't had many situations where we need to copy models or layers, but it's both good coding practice and helpful for things like LTFB.

(For those who need a refresher on the rule of three: [cppreference](http://en.cppreference.com/w/cpp/language/rule_of_three), [Wikipedia](https://en.wikipedia.org/wiki/Rule_of_three_(C%2B%2B_programming)), tl;dr: if you define one of a destructor, copy constructor, or a copy assignment operator, you _almost certainly_ require all three.)

**Comment by ndryden** [comment]
A further note: As of C++11, the automatic generation of the default copy constructor is deprecated if a user-defined destructor is present; it could switch to be deleted in a future version.

**Comment by ndryden** [comment]
Current status:
- [x] Optimizers
- [x] Metrics
- [x] Objective functions
- [x] `lbann_comm` (disabled, no copying)
- [ ] Callbacks
- [ ] Layers
- [ ] Data readers
- [ ] Models
- [ ] Other utilities

The semantics and implementation for copying layers and models may be a little awkward. When copying a model, we want a second, completely independent model, with exactly the same state as the original. When copying a layer on its own, however, we will probably end up with two layers that are "within" the same model, with the same previous/next pointers, etc. Note we also can't "re-setup" layers, because that will destroy the copied state. It therefore may not make much sense to copy layers independently of an entire model, which will need to handle carefully replumbing everything.

**Comment by ndryden** [comment]
Current state: Most things except the models now have copy constructors/copy assignment operators. I have also implement the virtual copy constructor pattern (via a virtual `copy` method), similar to what Elemental does, to enable copying through pointers to base classes ([details](https://en.wikibooks.org/wiki/More_C%2B%2B_Idioms/Virtual_Constructor)).

I have not handled the partitioned IO layers because of the `partitioned_minibatch_parallel_io` class, which keeps its own pointers to `generic_data_readers`, in addition to the `io_layer` (which has them via its `dataset`s). I don't want to copy them twice, which will likely break things. It seems like it should be possible to avoid storing them in the `partitioned_minibatch_parallel_io` layer.

I have not handled the `distributed_minibatch` input/target layers, because they're targeted for removal (I believe). I have not handled the `reconstruction_layer`, because I want to talk to @samadejacobs about what needs to be copied.

**Comment by ndryden** [comment]
@timmoon10 Need to copy over GPU data in the copy constructors/assignment operators. Currently, `Layer` will throw an exception to prevent getting into an undefined state.

**Comment by ndryden** [comment]
An issue to resolve with the data readers/io layers: The input and target layers expect to have pointers to the _same_ data readers. To avoid different models stomping over each other's data readers, they are copied. Right now, the input/target layers do the copies on their own, which results in them having separate data readers. The problem: who should do the copy, and how should the other layer be updated?

A few ideas:
- (My current stopgap approach:) The model does the copies as it is right now, then updates the target layer with the input layer's new data readers.
- Instead of having its own `dataset`/data reader instances, the target layer has a pointer to the input layer and its data readers.
- Associate datasets/data readers with the model instead of an input/target layer. (I like this less; what if we want to use multiple different datasets/input layers for a single model?)

**Comment by bvanessen** [comment]
The input layer has to have its own data readers by definition.  The target layers typically have pointers to the input layers data readers because they share the same metadata.  We have not yet had a case with target layers having their own data readers.  I think that the best approach may be to do a hybrid of your second option.  What I am envisioning is that if the target layer does not have a unique data reader then it has a null pointer for its local readers and has a pointer to the input layer and uses the input layer’s readers.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by ndryden** [comment]
As of 4ed15ec9efda9f96dd6a9057bf32acabdbed9cd6, it seems that stuff is working in a simple test, aside from the data reader issue above (I have a quick local hack).

I can take our dnn_mnist model, copy it, and train them separately; the first epochs match exactly, and they are very close thereafter (they use the same RNGs, so they shuffle data in a different order and we shouldn't expect the accuracies/losses to be identical).

**Comment by ndryden** [comment]
The `varmb-dev` branch now supports handling the above data reader issue, and will be merged to develop soon. All that remains is to handle the GPU case (cc @timmoon10) and a couple other cases (e.g. reconstruction layer).

**Comment by timmoon10** [comment]
As of 4789b3af64ca24a47d5be1e1338700fa8a136405, GPU objects are handled by the copy constructors and copy assignment operators. cab54d3bc3016fadb7db9a85bdf07d37311a42b1 adds a copy constructor and copy assignment operator for the reconstruction layer, although a little more work is needed to correctly set the pointer to the original layer (@samadejacobs).

**Comment by ndryden** [comment]
@samadejacobs What's the status of this for the reconstruction layer?

**Comment by samadejacobs** [comment]
Sorry, haven't been following this (Github won't allow me have two emails, so your messages go to my personal email). I would expect that reconstruction layer will be treated the same way as other target layers that have pointer to their input layers. It seems this was covered as part of your suggested idea on 07/06.

**Comment by ndryden** [comment]
Okay, then I believe we can declare this finished.
