### ISSUE TITLE
Layer indices

### ISSUE THREAD

**Issue by ndryden** [LLNL/lbann#92]
Currently, all our layers take a (manually-specified) index in their constructor. I propose removing this. Right now, `sequential_model` overrides what ever is set when its `add` method uses `set_index` to manually change the index to some sequential order (based on how the layers were added). Other model structures may do more complex things with indices.

Instead, I propose that an index is assigned by a model via `set_index` when a layer is added to it.

Thoughts?

Edit: Additional note, `sequential_model::setup` _also_ sets the index for each layer.

**Comment by bvanessen** [comment]
In general, I agree that the index should be set by the model rather than at the time of construction for the layer.  One consideration, is that if we add layers in a sequential fashion, this approach would work well.  However, if we want to insert a layer into a particular spot, how should we specify that?  Specifically, if we have a merge layer, how do we specify where the two previous layers sit.   I don’t think that we want to do this via dead reckoning with manual indices, however when we use a prototext description, how will we indicate that two layers are parallel versus serial?  Do we create a prototext group structure that contains multiple parallel layers and each group is sequential to the previous layer.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by davidHysom** [comment]
currently each layer in the prototext has in "index" and "parent" field. I can change the parent field to specify multiple parent layers. Is that sufficient?

________________________________

**Comment by davidHysom** [comment]
note: the indices in the prototext files do not correspond to indices in the model. Rather, their use is to represent a DAG, where the vertices are of course the layers.

________________________________

**Comment by bvanessen** [comment]
That modification to the parent field may be sufficient.  Do you make much use of the index field?

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by davidHysom** [comment]
it's currently not used; I included it for future development, and because it seemed like a good idea. Agree, child indices aren't needed.

________________________________

**Comment by timmoon10** [comment]
I like the idea of the model class setting the layer class's index variable. To make it a bit more general for DAGs, we could change it from an `int` to a `string` (either a user-provided name or a hash). Also, GPUs layers currently require knowledge of their child layers to correctly determine when to do GPU memory transfers.

**Comment by ndryden** [comment]
Another thing I just noticed: `io_layer`s always set their index to 0 in their constructor.

**Comment by timmoon10** [comment]
I think it would be worthwhile to replace `int m_index` with `std::string m_name`. In graph networks, the concept of layer indices is not very meaningful. In addition, this would would allow users to give layers useful mnemonics and not force them to renumber layers in their prototext file if they insert or delete a layer.

**Comment by bvanessen** [comment]
I think that is where we want to go. Can this wait for the next refactoring?


Brian C. Van Essen

vanessen1@llnl.gov<mailto:vanessen1@llnl.gov>

(w) 925-422-9300

(c) 925-290-5470

---

Sent from my iPhone

On Oct 6, 2017, at 4:43 PM, Tim Moon <notifications@github.com<mailto:notifications@github.com>> wrote:


I think it would be worthwhile to replace int m_index with std::string m_name. In graph networks, the concept of layer indices is not very meaningful. In addition, this would would allow users to give layers useful mnemonics and not force them to renumber layers in their prototext file if they insert or delete a layer.

**Comment by timmoon10** [comment]
I don't think it would be hard to internally change `int`s to `string`s. The most disruptive thing will probably be the need to change the "index" field in the prototext files to "name". We could hold off of that change though.

**Comment by davidHysom** [comment]
>renumber layers in their prototext file if they insert or delete a layer.



You should only need to change the index for a single layer if you add or delete a layer

________________________________

**Comment by davidHysom** [comment]
A few points:

  1.  the indices (currently ints) can be arbitrarily numbered, i.e, the input layer can have index: 42.
These indices do not directly correlate to the lbann layer indices.
  2.  currently the indices (and parent indices) aren't even used; rather, layers are added wrt the order they appear in the prototext file.
  3.  I'm in the process of adding the logic to actually use the prototext indices
  4.  So this is a good time to change 'indices' to 'name' and the type from 'int' to 'string.' I'll write a python script to make the change to all existing prototext files. I realize this doesn't address proposed changes to the sequential model indices -- but it's a step in that direction

________________________________

**Comment by bvanessen** [comment]
Okay sounds good.


Brian C. Van Essen

vanessen1@llnl.gov<mailto:vanessen1@llnl.gov>

(w) 925-422-9300

(c) 925-290-5470

---

Sent from my iPhone

On Oct 6, 2017, at 3:53 PM, davidHysom <notifications@github.com<mailto:notifications@github.com>> wrote:

A few points:

1. the indices (currently ints) can be arbitrarily numbered, i.e, the input layer can have index: 42.
These indices do not directly correlate to the lbann layer indices.
2. currently the indices (and parent indices) aren't even used; rather, layers are added wrt the order they appear in the prototext file.
3. I'm in the process of adding the logic to actually use the prototext indices
4. So this is a good time to change 'indices' to 'name' and the type from 'int' to 'string.' I'll write a python script to make the change to all existing prototext files. I realize this doesn't address proposed changes to the sequential model indices -- but it's a step in that direction

________________________________
