### ISSUE TITLE
nvcc fatal   : Unknown option 'pthread'

### ISSUE THREAD

**Issue by Raviteja1996** [LLNL/lbann#928]
Hi, I am trying to install Hydrogen. So I went and cloned from the GitHub. I made a build directory went into it and successfully did a cmake. But when I do make the following error is being shown. 

[ 73%] Linking CUDA device code CMakeFiles/EntrywiseMap.dir/cmake_device_link.o
nvcc fatal   : Unknown option 'pthread'
tests/CMakeFiles/EntrywiseMap.dir/build.make:99: recipe for target 'tests/CMakeFiles/EntrywiseMap.dir/cmake_device_link.o' failed
make[2]: *** [tests/CMakeFiles/EntrywiseMap.dir/cmake_device_link.o] Error 1
CMakeFiles/Makefile2:1506: recipe for target 'tests/CMakeFiles/EntrywiseMap.dir/all' failed
make[1]: *** [tests/CMakeFiles/EntrywiseMap.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by frobnitzem** [comment]
Was this resolved?  According to the following article, [the current fix is downgrading cmake to 3.10](https://peter.bloomfield.online/workaround-nvcc-pthread-issue/).  I'm having the same problem on an unrelated code with cmake 3.18.1.

**Comment by benson31** [comment]
The problem with respect to Hydrogen is generally Spectrum MPI adding this in the `INTERFACE_COMPILE_OPTIONS` of the `MPI::MPI_CXX` imported target. In LBANN, we [modify that target](https://github.com/LLNL/lbann/blob/develop/cmake/modules/SetupMPI.cmake#L32) to work around this. As long as you don't reset the `MPI::MPI_CXX` target after setting it up this way, this seems to work. I'm not sure this is consistent across our stack. I don't know that we currently use a lot of the newer features of CMake in LBANN, but I incorporate them in other work. Generally I see CMake as improving; I wouldn't recommend going backwards...
