### ISSUE TITLE
Reorganize Python interface

### ISSUE THREAD

**Issue by timmoon10** [LLNL/lbann#946]
The Python interface was originally implemented as a prototext generator, but it has quickly grown in scope. With PR #941, I think it is ready to be a frontend for configuring and running LBANN experiments. I think the following changes would reflect this new role:
- [x] Move the Python code from `scripts/proto` to a top-level directory called `python`.
- [x] Move the core functionality out of `proto.py`, either into `__init__.py` (the base layer class becomes `lbann.Layer`) or into separate Python files (the layer class becomes something like `lbann.layer.Layer`).
- [ ] The build system installs the Python module in the install directory.

**Comment by ndryden** [comment]
Note we don't necessarily have to move the code into `__init__.py`. It can load what it needs and put things into the namespace.
