### ISSUE TITLE
Build failure with Conduit

### ISSUE THREAD

**Issue by timmoon10** [LLNL/lbann#952]
When I try directly following the Spack build instructions (commit 3cddaf212a3dd6be3c9f1016edfcdf7bf101c3cb, Pascal), I get the following error:
```
/usr/WS1/moon13/src/lbann/model_zoo/jag_utils/generate_corrupt_samples.cpp:33:10: fatal error: conduit_relay_io_handle.hpp: No such file or directory
 #include "conduit_relay_io_handle.hpp"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

I don't see this problem when I use `scripts/build_lbann_lc.sh`, so all signs point to something with Conduit.

**Comment by timmoon10** [comment]
`model_zoo/jag_utils/generate_corrupt_samples.cpp` was added yesterday in PR #944.

**Comment by davidHysom** [comment]
conduit_relay_io_handle.hpp is a very recently added class to conduit; it was introduced in the release seven days ago. This makes me think that you're somehow using an older version of conduit. I only started using spack a few days ago, and have not had a problem with conduit. Conduit will soon be a requirement for building lbann -- if you want to use the new data_store classes.
