### ISSUE TITLE
Hanging when some nodes have no data

### ISSUE THREAD

**Issue by ndryden** [LLNL/lbann#97]
LBANN seems to hang when there are ranks that have no data (i.e. no samples) to compute with. This commonly occurs when the last mini-batch has fewer samples than there are ranks when using the partitioned data reader.

Running on the 10-class ImageNet subset with 256 ranks and a mini-batch size of 256 will produce this.

**Comment by bvanessen** [comment]
Fixed in commit 6829b3135fe07d62a911db04d2d516e98fcbe4ca
