### ISSUE TITLE
Models that run strictly on model parallelism

### ISSUE THREAD

**Issue by Raviteja1996** [LLNL/lbann#986]
Hi, I have seen architecture of some of the models which run on strictly model parallelism like pilot1 and jag(except the input layers). The remaining models are either data parallelism or combination of both. I would like to run the models which are performing model parallelism and learn. But the datasets for both of them are not public. I have tried to run other models(like mnist, imagenet) with model parallelism but they are not that effective. So any help in my case!

**Comment by ndryden** [comment]
Models that run entirely on model parallelism would need to be made up entirely of fully-connected layers (plus activations, etc.). It should be easy to construct such a model for MNIST and have it learn, although it is not likely to be terribly useful compared to convolutional networks.

You might also look at language models, which tend to involve big fully-connected layers. We do not currently have any in our model zoo.
